-- Krovara — Prosody configuration (dev).
--
-- This file is the source of truth for the dev XMPP server. Production is
-- the same shape with TLS + real cert paths (session 15).
--
-- Storage: PostgreSQL ("krovara" DB). Prosody creates and owns its own
-- prosody_* tables on first start; nothing in migrations/ touches them.
--
-- Auth: in session 08 we keep the built-in internal_hashed provider and
-- create users via prosodyctl. Session 09 swaps this for a JWT/HTTP shim
-- backed by the Go API.

-- General admins (JIDs).
admins = { "admin@krovara.local" }

-- Plugin paths Prosody scans for modules in addition to its defaults.
plugin_paths = { "/usr/lib/prosody/modules", "/etc/prosody/community-modules" }

-- Module list applied to every VirtualHost unless overridden.
modules_enabled = {
    -- Core / required.
    "roster";
    "saslauth";
    "tls";
    "dialback";
    "disco";
    "private";
    "vcard4";
    "vcard_legacy";
    "version";
    "uptime";
    "time";
    "ping";
    "register";
    "admin_adhoc";
    "blocklist";

    -- Messaging features.
    "carbons";    -- XEP-0280 multi-device delivery
    "mam";        -- XEP-0313 message archive
    -- "smacks";  -- XEP-0198 — community module on 0.11; skip in dev.
    "csi_simple"; -- mobile-friendly stanza filtering

    -- Transports.
    "bosh";
    "websocket";  -- RFC 7395 — exposed at /xmpp-websocket

    -- HTTP auth bridge (community module — installed via prosody-modules).
    -- Active only when authentication = "http" (see auth block below).
    "auth_http";

    -- Group / pub-sub.
    "pep";

    -- HTTP base for websocket/bosh.
    "http";
}

modules_disabled = {}

-- Storage.
storage = "sql"
sql = {
    driver   = "PostgreSQL";
    database = os.getenv("PROSODY_DB_NAME") or "krovara";
    host     = os.getenv("PROSODY_DB_HOST") or "postgres";
    port     = tonumber(os.getenv("PROSODY_DB_PORT") or "5432");
    username = os.getenv("PROSODY_DB_USER") or "krovara";
    password = os.getenv("PROSODY_DB_PASSWORD") or "krovara";
}

-- MAM defaults — keep everything; cleanup is a River job (session 14).
archive_expires_after = "never"
default_archive_policy = true
max_archive_query_results = 100

-- Authentication backend.
--
-- Session 09 (ADR-007): dynamic auth via HTTP callback to the Go API. The
-- web client mints a short-lived token through /api/xmpp/token and uses it
-- as the XMPP password; Prosody forwards (user, pass) to /internal/xmpp/auth
-- which validates and consumes the token.
--
-- Falls back to `internal_hashed` if KROVARA_XMPP_AUTH_URL is unset so
-- `prosodyctl adduser` (session 08 smoke flow) keeps working.
local auth_url = os.getenv("KROVARA_XMPP_AUTH_URL")
if auth_url and auth_url ~= "" then
    authentication = "http"
    http_auth_url = auth_url
else
    authentication = "internal_hashed"
end

-- Network bind: listen on all interfaces inside the container.
interfaces = { "*" }
c2s_ports = { 5222 }
s2s_ports = { 5269 }

-- Component (XEP-0114) port for bots. Loaded from
-- /etc/prosody/components.cfg.lua if it exists — that file is generated
-- by the operator from `POST /api/spaces/:id/bots` responses (one entry
-- per bot) and reloaded with `prosodyctl reload`. See sessions/20-bots.md.
component_ports = { 5347 }
component_interface = "0.0.0.0"

-- HTTP listener (BOSH + WebSocket).
http_ports          = { 5280 }
http_interfaces     = { "*" }
https_ports         = {}
http_external_url   = os.getenv("PROSODY_HTTP_EXTERNAL_URL") or "http://localhost:5280/"
consider_websocket_secure = true   -- dev: tolerate ws:// from same-origin clients
cross_domain_websocket    = true

-- TLS: dev certs are generated by scripts/dev-prosody-certs.sh.
certificates = "certs"

-- Logging — JSON-ish lines to stderr for `docker compose logs`.
log = {
    { levels = { min = "debug" }, to = "console" };
}

-- ------------------------------------------------------------------
-- VirtualHost
-- ------------------------------------------------------------------
VirtualHost "krovara.local"
    -- Self-signed dev cert (mounted at /etc/prosody/certs/krovara.local.{crt,key}).
    ssl = {
        certificate = "/etc/prosody/certs/krovara.local.crt";
        key         = "/etc/prosody/certs/krovara.local.key";
    }

-- ------------------------------------------------------------------
-- Components
-- ------------------------------------------------------------------
Component "conference.krovara.local" "muc"
    modules_enabled = { "muc_mam" }
    name = "Krovara channels"
    -- Allow any authenticated local user to auto-create a room on first
    -- join. We rely on the API-layer permissions to gate who can see
    -- which channel UUIDs in the first place.
    restrict_room_creation = false
    -- Rooms survive being empty. Otherwise Prosody destroys them on the
    -- last leave and the MAM archive goes with them.
    muc_room_default_persistent = true
    muc_room_default_public      = true
    muc_room_default_members_only = false
    muc_room_default_change_subject = false
    muc_room_default_allow_member_invites = true
    muc_room_default_public_jids = true
    -- Force archiving on every room regardless of per-room config — saves
    -- us having to send a config form after creation.
    muc_log_all_rooms = true
    muc_log_by_default = true
    -- XEP-0045 §10.1.3: by default, Prosody locks a newly-created room
    -- until the owner submits a config form. With our lazy-creation flow
    -- nobody ever does, so the room stays locked and everyone but the
    -- creator is bounced. Disable the lock — defaults are already what
    -- we want.
    muc_room_locking = false

Component "pubsub.krovara.local" "pubsub"

-- Bot components.
--
-- Per-bot Lua snippets are written by the Krovara API into
-- /etc/prosody/components.d/ (one `bot-<short>.cfg.lua` per bot, see
-- internal/bots). We iterate that dir on every startup / reload and
-- dofile each file. A stale snippet pointing at a deleted bot is
-- harmless beyond a warning.
--
-- The legacy single-file path `/etc/prosody/components.cfg.lua` is still
-- supported for ops who manage Prosody config by hand.
local lfs_ok, lfs = pcall(require, "lfs")
if lfs_ok then
    local dir = "/etc/prosody/components.d/"
    if lfs.attributes(dir, "mode") == "directory" then
        for f in lfs.dir(dir) do
            if f:sub(-#".cfg.lua") == ".cfg.lua" then
                pcall(dofile, dir .. f)
            end
        end
    end
end
local has_legacy, _ = pcall(dofile, "/etc/prosody/components.cfg.lua")
_ = has_legacy

-- HTTP file share (XEP-0363) — needs mod_http_file_share (Prosody 0.12+)
-- or mod_http_upload (community). Both absent from the 0.11 image; dev
-- ships without file uploads. Re-enable once we upgrade to 0.12 in compose:
--
-- Component "upload.krovara.local" "http_file_share"
--     http_file_share_size_limit    = 100 * 1024 * 1024
--     http_file_share_daily_quota   = 1024 * 1024 * 1024
--     http_file_share_expires_after = 7 * 24 * 60 * 60
