// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIToken = `-- name: CreateAPIToken :one
INSERT INTO api_tokens (user_id, name, token_hash, prefix, scopes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, prefix, scopes, last_used_at, created_at
`

type CreateAPITokenParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	TokenHash string      `json:"token_hash"`
	Prefix    string      `json:"prefix"`
	Scopes    []string    `json:"scopes"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.Prefix,
		arg.Scopes,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIToken = `-- name: DeleteAPIToken :exec
DELETE FROM api_tokens WHERE id = $1 AND user_id = $2
`

type DeleteAPITokenParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error {
	_, err := q.db.Exec(ctx, deleteAPIToken, arg.ID, arg.UserID)
	return err
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT id, user_id, name, token_hash, prefix, scopes, last_used_at, created_at FROM api_tokens WHERE token_hash = $1
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.Prefix,
		&i.Scopes,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, user_id, name, token_hash, prefix, scopes, last_used_at, created_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserAPITokens(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listUserAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.Prefix,
			&i.Scopes,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
