// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_logs (space_id, actor_id, action, target_id, metadata)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, space_id, actor_id, action, target_id, metadata, created_at
`

type CreateAuditLogParams struct {
	SpaceID  pgtype.UUID `json:"space_id"`
	ActorID  pgtype.UUID `json:"actor_id"`
	Action   string      `json:"action"`
	TargetID pgtype.UUID `json:"target_id"`
	Metadata []byte      `json:"metadata"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.SpaceID,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ActorID,
		&i.Action,
		&i.TargetID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceAuditLogs = `-- name: ListSpaceAuditLogs :many
SELECT id, space_id, actor_id, action, target_id, metadata, created_at FROM audit_logs
 WHERE space_id = $1
 ORDER BY created_at DESC
 LIMIT $2
`

type ListSpaceAuditLogsParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListSpaceAuditLogs(ctx context.Context, arg ListSpaceAuditLogsParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listSpaceAuditLogs, arg.SpaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ActorID,
			&i.Action,
			&i.TargetID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
