// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bans.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBan = `-- name: CreateBan :one
INSERT INTO bans (space_id, user_id, moderator_id, reason)
VALUES ($1, $2, $3, $4)
RETURNING id, space_id, user_id, moderator_id, reason, created_at
`

type CreateBanParams struct {
	SpaceID     pgtype.UUID `json:"space_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ModeratorID pgtype.UUID `json:"moderator_id"`
	Reason      *string     `json:"reason"`
}

func (q *Queries) CreateBan(ctx context.Context, arg CreateBanParams) (Ban, error) {
	row := q.db.QueryRow(ctx, createBan,
		arg.SpaceID,
		arg.UserID,
		arg.ModeratorID,
		arg.Reason,
	)
	var i Ban
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.ModeratorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBan = `-- name: DeleteBan :exec
DELETE FROM bans
 WHERE space_id = $1 AND user_id = $2
`

type DeleteBanParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteBan(ctx context.Context, arg DeleteBanParams) error {
	_, err := q.db.Exec(ctx, deleteBan, arg.SpaceID, arg.UserID)
	return err
}

const getBan = `-- name: GetBan :one
SELECT id, space_id, user_id, moderator_id, reason, created_at FROM bans
 WHERE space_id = $1 AND user_id = $2
`

type GetBanParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetBan(ctx context.Context, arg GetBanParams) (Ban, error) {
	row := q.db.QueryRow(ctx, getBan, arg.SpaceID, arg.UserID)
	var i Ban
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.ModeratorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const isUserBanned = `-- name: IsUserBanned :one
SELECT EXISTS (
  SELECT 1 FROM bans WHERE space_id = $1 AND user_id = $2
) AS banned
`

type IsUserBannedParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsUserBanned(ctx context.Context, arg IsUserBannedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isUserBanned, arg.SpaceID, arg.UserID)
	var banned bool
	err := row.Scan(&banned)
	return banned, err
}

const listSpaceBans = `-- name: ListSpaceBans :many
SELECT id, space_id, user_id, moderator_id, reason, created_at FROM bans WHERE space_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpaceBans(ctx context.Context, spaceID pgtype.UUID) ([]Ban, error) {
	rows, err := q.db.Query(ctx, listSpaceBans, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Ban{}
	for rows.Next() {
		var i Ban
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.ModeratorID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
