// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByStripeCustomer = `-- name: GetUserByStripeCustomer :one
SELECT id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified FROM users WHERE stripe_customer_id = $1
`

func (q *Queries) GetUserByStripeCustomer(ctx context.Context, stripeCustomerID *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByStripeCustomer, stripeCustomerID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.Disabled,
		&i.WhoCanAdd,
		&i.BannerKey,
		&i.Bio,
		&i.Pronouns,
		&i.Links,
		&i.AccentColor,
		&i.SignupIpHash,
		&i.Badges,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.EmailVerified,
	)
	return i, err
}

const setUserStripeCustomer = `-- name: SetUserStripeCustomer :exec
UPDATE users SET stripe_customer_id = $2 WHERE id = $1
`

type SetUserStripeCustomerParams struct {
	ID               pgtype.UUID `json:"id"`
	StripeCustomerID *string     `json:"stripe_customer_id"`
}

func (q *Queries) SetUserStripeCustomer(ctx context.Context, arg SetUserStripeCustomerParams) error {
	_, err := q.db.Exec(ctx, setUserStripeCustomer, arg.ID, arg.StripeCustomerID)
	return err
}

const setUserSubscription = `-- name: SetUserSubscription :exec
UPDATE users
   SET stripe_subscription_id = $1,
       subscription_status    = $2,
       current_period_end     = $3,
       tier                   = $4
 WHERE stripe_customer_id = $5
`

type SetUserSubscriptionParams struct {
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	SubscriptionStatus   *string            `json:"subscription_status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	Tier                 string             `json:"tier"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
}

func (q *Queries) SetUserSubscription(ctx context.Context, arg SetUserSubscriptionParams) error {
	_, err := q.db.Exec(ctx, setUserSubscription,
		arg.StripeSubscriptionID,
		arg.SubscriptionStatus,
		arg.CurrentPeriodEnd,
		arg.Tier,
		arg.StripeCustomerID,
	)
	return err
}
