// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBot = `-- name: CreateBot :one
INSERT INTO bots (space_id, name, component_jid, secret_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, space_id, name, component_jid, secret_hash, created_at
`

type CreateBotParams struct {
	SpaceID      pgtype.UUID `json:"space_id"`
	Name         string      `json:"name"`
	ComponentJid string      `json:"component_jid"`
	SecretHash   string      `json:"secret_hash"`
}

func (q *Queries) CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error) {
	row := q.db.QueryRow(ctx, createBot,
		arg.SpaceID,
		arg.Name,
		arg.ComponentJid,
		arg.SecretHash,
	)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.ComponentJid,
		&i.SecretHash,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBot = `-- name: DeleteBot :exec
DELETE FROM bots WHERE id = $1
`

func (q *Queries) DeleteBot(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBot, id)
	return err
}

const getBot = `-- name: GetBot :one
SELECT id, space_id, name, component_jid, secret_hash, created_at FROM bots WHERE id = $1
`

func (q *Queries) GetBot(ctx context.Context, id pgtype.UUID) (Bot, error) {
	row := q.db.QueryRow(ctx, getBot, id)
	var i Bot
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.ComponentJid,
		&i.SecretHash,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceBots = `-- name: ListSpaceBots :many
SELECT id, space_id, name, component_jid, secret_hash, created_at FROM bots WHERE space_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpaceBots(ctx context.Context, spaceID pgtype.UUID) ([]Bot, error) {
	rows, err := q.db.Query(ctx, listSpaceBots, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bot{}
	for rows.Next() {
		var i Bot
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.ComponentJid,
			&i.SecretHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
