// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (space_id, name, position)
VALUES ($1, $2, COALESCE($3, (
    SELECT COALESCE(MAX(position), -1) + 1 FROM categories WHERE space_id = $1
)))
RETURNING id, space_id, name, position, created_at
`

type CreateCategoryParams struct {
	SpaceID  pgtype.UUID `json:"space_id"`
	Name     string      `json:"name"`
	Position interface{} `json:"position"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.SpaceID, arg.Name, arg.Position)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCategory = `-- name: DeleteCategory :exec
DELETE FROM categories WHERE id = $1
`

func (q *Queries) DeleteCategory(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCategory, id)
	return err
}

const getCategory = `-- name: GetCategory :one
SELECT id, space_id, name, position, created_at FROM categories WHERE id = $1
`

func (q *Queries) GetCategory(ctx context.Context, id pgtype.UUID) (Category, error) {
	row := q.db.QueryRow(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceCategories = `-- name: ListSpaceCategories :many
SELECT id, space_id, name, position, created_at FROM categories
 WHERE space_id = $1
 ORDER BY position, created_at
`

func (q *Queries) ListSpaceCategories(ctx context.Context, spaceID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listSpaceCategories, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Category{}
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCategory = `-- name: UpdateCategory :one
UPDATE categories
   SET name     = COALESCE($1,     name),
       position = COALESCE($2, position)
 WHERE id = $3
RETURNING id, space_id, name, position, created_at
`

type UpdateCategoryParams struct {
	Name     *string     `json:"name"`
	Position *int32      `json:"position"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, updateCategory, arg.Name, arg.Position, arg.ID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
