// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: channels.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels (space_id, name, topic, type, position, is_private, category_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, space_id, name, topic, type, position, is_private, created_at, locked, locked_by, locked_at, category_id, slowmode_seconds, nsfw, read_only, icon_emoji
`

type CreateChannelParams struct {
	SpaceID    pgtype.UUID `json:"space_id"`
	Name       string      `json:"name"`
	Topic      *string     `json:"topic"`
	Type       *string     `json:"type"`
	Position   *int32      `json:"position"`
	IsPrivate  *bool       `json:"is_private"`
	CategoryID pgtype.UUID `json:"category_id"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, createChannel,
		arg.SpaceID,
		arg.Name,
		arg.Topic,
		arg.Type,
		arg.Position,
		arg.IsPrivate,
		arg.CategoryID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.Locked,
		&i.LockedBy,
		&i.LockedAt,
		&i.CategoryID,
		&i.SlowmodeSeconds,
		&i.Nsfw,
		&i.ReadOnly,
		&i.IconEmoji,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :exec
DELETE FROM channels WHERE id = $1
`

func (q *Queries) DeleteChannel(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChannel, id)
	return err
}

const getChannel = `-- name: GetChannel :one
SELECT id, space_id, name, topic, type, position, is_private, created_at, locked, locked_by, locked_at, category_id, slowmode_seconds, nsfw, read_only, icon_emoji FROM channels WHERE id = $1
`

func (q *Queries) GetChannel(ctx context.Context, id pgtype.UUID) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.Locked,
		&i.LockedBy,
		&i.LockedAt,
		&i.CategoryID,
		&i.SlowmodeSeconds,
		&i.Nsfw,
		&i.ReadOnly,
		&i.IconEmoji,
	)
	return i, err
}

const listSpaceChannels = `-- name: ListSpaceChannels :many
SELECT id, space_id, name, topic, type, position, is_private, created_at, locked, locked_by, locked_at, category_id, slowmode_seconds, nsfw, read_only, icon_emoji FROM channels
 WHERE space_id = $1
 ORDER BY position, created_at
`

func (q *Queries) ListSpaceChannels(ctx context.Context, spaceID pgtype.UUID) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listSpaceChannels, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Topic,
			&i.Type,
			&i.Position,
			&i.IsPrivate,
			&i.CreatedAt,
			&i.Locked,
			&i.LockedBy,
			&i.LockedAt,
			&i.CategoryID,
			&i.SlowmodeSeconds,
			&i.Nsfw,
			&i.ReadOnly,
			&i.IconEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveChannel = `-- name: MoveChannel :one

UPDATE channels
   SET category_id = $1,
       position    = $2
 WHERE id = $3
RETURNING id, space_id, name, topic, type, position, is_private, created_at, locked, locked_by, locked_at, category_id, slowmode_seconds, nsfw, read_only, icon_emoji
`

type MoveChannelParams struct {
	CategoryID pgtype.UUID `json:"category_id"`
	Position   *int32      `json:"position"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) MoveChannel(ctx context.Context, arg MoveChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, moveChannel, arg.CategoryID, arg.Position, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.Locked,
		&i.LockedBy,
		&i.LockedAt,
		&i.CategoryID,
		&i.SlowmodeSeconds,
		&i.Nsfw,
		&i.ReadOnly,
		&i.IconEmoji,
	)
	return i, err
}

const setChannelLock = `-- name: SetChannelLock :one
UPDATE channels
   SET locked    = $1,
       locked_by = CASE WHEN $1 THEN $2::uuid ELSE NULL END,
       locked_at = CASE WHEN $1 THEN NOW() ELSE NULL END
 WHERE id = $3
RETURNING id, space_id, name, topic, type, position, is_private, created_at, locked, locked_by, locked_at, category_id, slowmode_seconds, nsfw, read_only, icon_emoji
`

type SetChannelLockParams struct {
	Locked   bool        `json:"locked"`
	LockedBy pgtype.UUID `json:"locked_by"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) SetChannelLock(ctx context.Context, arg SetChannelLockParams) (Channel, error) {
	row := q.db.QueryRow(ctx, setChannelLock, arg.Locked, arg.LockedBy, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.Locked,
		&i.LockedBy,
		&i.LockedAt,
		&i.CategoryID,
		&i.SlowmodeSeconds,
		&i.Nsfw,
		&i.ReadOnly,
		&i.IconEmoji,
	)
	return i, err
}

const updateChannel = `-- name: UpdateChannel :one
UPDATE channels
   SET name             = COALESCE($1,             name),
       topic            = COALESCE($2,            topic),
       position         = COALESCE($3,         position),
       is_private       = COALESCE($4,       is_private),
       slowmode_seconds = COALESCE($5, slowmode_seconds),
       nsfw             = COALESCE($6,             nsfw),
       read_only        = COALESCE($7,        read_only),
       icon_emoji       = COALESCE($8,       icon_emoji)
 WHERE id = $9
RETURNING id, space_id, name, topic, type, position, is_private, created_at, locked, locked_by, locked_at, category_id, slowmode_seconds, nsfw, read_only, icon_emoji
`

type UpdateChannelParams struct {
	Name            *string     `json:"name"`
	Topic           *string     `json:"topic"`
	Position        *int32      `json:"position"`
	IsPrivate       *bool       `json:"is_private"`
	SlowmodeSeconds *int32      `json:"slowmode_seconds"`
	Nsfw            *bool       `json:"nsfw"`
	ReadOnly        *bool       `json:"read_only"`
	IconEmoji       *string     `json:"icon_emoji"`
	ID              pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannel,
		arg.Name,
		arg.Topic,
		arg.Position,
		arg.IsPrivate,
		arg.SlowmodeSeconds,
		arg.Nsfw,
		arg.ReadOnly,
		arg.IconEmoji,
		arg.ID,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Topic,
		&i.Type,
		&i.Position,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.Locked,
		&i.LockedBy,
		&i.LockedAt,
		&i.CategoryID,
		&i.SlowmodeSeconds,
		&i.Nsfw,
		&i.ReadOnly,
		&i.IconEmoji,
	)
	return i, err
}
