// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: discovery.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const delistSpace = `-- name: DelistSpace :exec
UPDATE space_listings SET delisted_at = NOW() WHERE space_id = $1
`

func (q *Queries) DelistSpace(ctx context.Context, spaceID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, delistSpace, spaceID)
	return err
}

const exploreListings = `-- name: ExploreListings :many

SELECT l.space_id, l.category, l.member_count, l.listed_at,
       s.name, s.description, s.icon_key, s.banner_key, s.tags, s.language, s.vanity_slug
  FROM space_listings l
  JOIN spaces s ON s.id = l.space_id
 WHERE l.delisted_at IS NULL
   AND ($1::text = '' OR l.category = $1)
   AND ($2::text = '' OR s.name ILIKE '%' || $2 || '%' OR COALESCE(s.description,'') ILIKE '%' || $2 || '%')
 ORDER BY l.member_count DESC, l.listed_at DESC
 LIMIT $3
`

type ExploreListingsParams struct {
	Column1 string `json:"column_1"`
	Column2 string `json:"column_2"`
	Limit   int32  `json:"limit"`
}

type ExploreListingsRow struct {
	SpaceID     pgtype.UUID        `json:"space_id"`
	Category    string             `json:"category"`
	MemberCount int32              `json:"member_count"`
	ListedAt    pgtype.Timestamptz `json:"listed_at"`
	Name        string             `json:"name"`
	Description *string            `json:"description"`
	IconKey     *string            `json:"icon_key"`
	BannerKey   *string            `json:"banner_key"`
	Tags        []string           `json:"tags"`
	Language    *string            `json:"language"`
	VanitySlug  *string            `json:"vanity_slug"`
}

func (q *Queries) ExploreListings(ctx context.Context, arg ExploreListingsParams) ([]ExploreListingsRow, error) {
	rows, err := q.db.Query(ctx, exploreListings, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExploreListingsRow{}
	for rows.Next() {
		var i ExploreListingsRow
		if err := rows.Scan(
			&i.SpaceID,
			&i.Category,
			&i.MemberCount,
			&i.ListedAt,
			&i.Name,
			&i.Description,
			&i.IconKey,
			&i.BannerKey,
			&i.Tags,
			&i.Language,
			&i.VanitySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListing = `-- name: GetListing :one
SELECT space_id, category, member_count, listed_at, delisted_at FROM space_listings WHERE space_id = $1
`

func (q *Queries) GetListing(ctx context.Context, spaceID pgtype.UUID) (SpaceListing, error) {
	row := q.db.QueryRow(ctx, getListing, spaceID)
	var i SpaceListing
	err := row.Scan(
		&i.SpaceID,
		&i.Category,
		&i.MemberCount,
		&i.ListedAt,
		&i.DelistedAt,
	)
	return i, err
}

const upsertListing = `-- name: UpsertListing :one

INSERT INTO space_listings (space_id, category, member_count, delisted_at)
VALUES ($1, $2, (SELECT COUNT(*) FROM members WHERE space_id = $1), NULL)
ON CONFLICT (space_id)
DO UPDATE SET category = EXCLUDED.category,
              member_count = EXCLUDED.member_count,
              delisted_at = NULL,
              listed_at = NOW()
RETURNING space_id, category, member_count, listed_at, delisted_at
`

type UpsertListingParams struct {
	SpaceID  pgtype.UUID `json:"space_id"`
	Category string      `json:"category"`
}

func (q *Queries) UpsertListing(ctx context.Context, arg UpsertListingParams) (SpaceListing, error) {
	row := q.db.QueryRow(ctx, upsertListing, arg.SpaceID, arg.Category)
	var i SpaceListing
	err := row.Scan(
		&i.SpaceID,
		&i.Category,
		&i.MemberCount,
		&i.ListedAt,
		&i.DelistedAt,
	)
	return i, err
}
