// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dm_groups.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDMGroupMember = `-- name: AddDMGroupMember :exec
INSERT INTO dm_group_members (group_id, user_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddDMGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddDMGroupMember(ctx context.Context, arg AddDMGroupMemberParams) error {
	_, err := q.db.Exec(ctx, addDMGroupMember, arg.GroupID, arg.UserID)
	return err
}

const countDMGroupMembers = `-- name: CountDMGroupMembers :one
SELECT COUNT(*) FROM dm_group_members WHERE group_id = $1
`

func (q *Queries) CountDMGroupMembers(ctx context.Context, groupID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDMGroupMembers, groupID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDMGroup = `-- name: CreateDMGroup :one
INSERT INTO dm_groups (owner_id, name) VALUES ($1, $2) RETURNING id, owner_id, name, icon_key, created_at
`

type CreateDMGroupParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    *string     `json:"name"`
}

func (q *Queries) CreateDMGroup(ctx context.Context, arg CreateDMGroupParams) (DmGroup, error) {
	row := q.db.QueryRow(ctx, createDMGroup, arg.OwnerID, arg.Name)
	var i DmGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
	)
	return i, err
}

const createDMGroupInvite = `-- name: CreateDMGroupInvite :exec
INSERT INTO dm_group_invites (code, group_id, created_by) VALUES ($1, $2, $3)
`

type CreateDMGroupInviteParams struct {
	Code      string      `json:"code"`
	GroupID   pgtype.UUID `json:"group_id"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDMGroupInvite(ctx context.Context, arg CreateDMGroupInviteParams) error {
	_, err := q.db.Exec(ctx, createDMGroupInvite, arg.Code, arg.GroupID, arg.CreatedBy)
	return err
}

const createDMGroupMessage = `-- name: CreateDMGroupMessage :one
INSERT INTO dm_group_messages (group_id, author_id, body)
VALUES ($1, $2, $3) RETURNING id, group_id, author_id, body, created_at
`

type CreateDMGroupMessageParams struct {
	GroupID  pgtype.UUID `json:"group_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateDMGroupMessage(ctx context.Context, arg CreateDMGroupMessageParams) (DmGroupMessage, error) {
	row := q.db.QueryRow(ctx, createDMGroupMessage, arg.GroupID, arg.AuthorID, arg.Body)
	var i DmGroupMessage
	err := row.Scan(
		&i.ID,
		&i.GroupID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDMGroup = `-- name: DeleteDMGroup :exec
DELETE FROM dm_groups WHERE id = $1
`

func (q *Queries) DeleteDMGroup(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDMGroup, id)
	return err
}

const deleteDMGroupInvite = `-- name: DeleteDMGroupInvite :exec
DELETE FROM dm_group_invites WHERE code = $1 AND group_id = $2
`

type DeleteDMGroupInviteParams struct {
	Code    string      `json:"code"`
	GroupID pgtype.UUID `json:"group_id"`
}

func (q *Queries) DeleteDMGroupInvite(ctx context.Context, arg DeleteDMGroupInviteParams) error {
	_, err := q.db.Exec(ctx, deleteDMGroupInvite, arg.Code, arg.GroupID)
	return err
}

const getDMGroup = `-- name: GetDMGroup :one
SELECT id, owner_id, name, icon_key, created_at FROM dm_groups WHERE id = $1
`

func (q *Queries) GetDMGroup(ctx context.Context, id pgtype.UUID) (DmGroup, error) {
	row := q.db.QueryRow(ctx, getDMGroup, id)
	var i DmGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
	)
	return i, err
}

const getDMGroupInvite = `-- name: GetDMGroupInvite :one
SELECT code, group_id, created_by, created_at FROM dm_group_invites WHERE code = $1
`

func (q *Queries) GetDMGroupInvite(ctx context.Context, code string) (DmGroupInvite, error) {
	row := q.db.QueryRow(ctx, getDMGroupInvite, code)
	var i DmGroupInvite
	err := row.Scan(
		&i.Code,
		&i.GroupID,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const isDMGroupMember = `-- name: IsDMGroupMember :one
SELECT EXISTS (SELECT 1 FROM dm_group_members WHERE group_id = $1 AND user_id = $2)
`

type IsDMGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) IsDMGroupMember(ctx context.Context, arg IsDMGroupMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isDMGroupMember, arg.GroupID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listDMGroupInvites = `-- name: ListDMGroupInvites :many
SELECT code, created_at FROM dm_group_invites WHERE group_id = $1 ORDER BY created_at DESC
`

type ListDMGroupInvitesRow struct {
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDMGroupInvites(ctx context.Context, groupID pgtype.UUID) ([]ListDMGroupInvitesRow, error) {
	rows, err := q.db.Query(ctx, listDMGroupInvites, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDMGroupInvitesRow{}
	for rows.Next() {
		var i ListDMGroupInvitesRow
		if err := rows.Scan(&i.Code, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMGroupMembers = `-- name: ListDMGroupMembers :many
SELECT u.id, u.username, COALESCE(u.display_name, u.username) AS display_name, u.avatar_key, m.joined_at
  FROM dm_group_members m
  JOIN users u ON u.id = m.user_id
 WHERE m.group_id = $1
 ORDER BY m.joined_at
`

type ListDMGroupMembersRow struct {
	ID          pgtype.UUID        `json:"id"`
	Username    string             `json:"username"`
	DisplayName string             `json:"display_name"`
	AvatarKey   *string            `json:"avatar_key"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListDMGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListDMGroupMembersRow, error) {
	rows, err := q.db.Query(ctx, listDMGroupMembers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDMGroupMembersRow{}
	for rows.Next() {
		var i ListDMGroupMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMGroupMessages = `-- name: ListDMGroupMessages :many
SELECT m.id, m.group_id, m.author_id, m.body, m.created_at,
       u.username, u.avatar_key
  FROM dm_group_messages m
  JOIN users u ON u.id = m.author_id
 WHERE m.group_id = $1 AND ($3::timestamptz IS NULL OR m.created_at < $3)
 ORDER BY m.created_at DESC
 LIMIT $2
`

type ListDMGroupMessagesParams struct {
	GroupID pgtype.UUID        `json:"group_id"`
	Limit   int32              `json:"limit"`
	Before  pgtype.Timestamptz `json:"before"`
}

type ListDMGroupMessagesRow struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Username  string             `json:"username"`
	AvatarKey *string            `json:"avatar_key"`
}

func (q *Queries) ListDMGroupMessages(ctx context.Context, arg ListDMGroupMessagesParams) ([]ListDMGroupMessagesRow, error) {
	rows, err := q.db.Query(ctx, listDMGroupMessages, arg.GroupID, arg.Limit, arg.Before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDMGroupMessagesRow{}
	for rows.Next() {
		var i ListDMGroupMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
			&i.Username,
			&i.AvatarKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutualDMGroups = `-- name: ListMutualDMGroups :many
SELECT g.id, g.name, g.icon_key
  FROM dm_groups g
 WHERE g.id IN (SELECT m.group_id FROM dm_group_members m WHERE m.user_id = $1)
   AND g.id IN (SELECT m.group_id FROM dm_group_members m WHERE m.user_id = $2)
 ORDER BY g.created_at DESC
`

type ListMutualDMGroupsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

type ListMutualDMGroupsRow struct {
	ID      pgtype.UUID `json:"id"`
	Name    *string     `json:"name"`
	IconKey *string     `json:"icon_key"`
}

func (q *Queries) ListMutualDMGroups(ctx context.Context, arg ListMutualDMGroupsParams) ([]ListMutualDMGroupsRow, error) {
	rows, err := q.db.Query(ctx, listMutualDMGroups, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMutualDMGroupsRow{}
	for rows.Next() {
		var i ListMutualDMGroupsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IconKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyDMGroups = `-- name: ListMyDMGroups :many
SELECT g.id, g.name, g.icon_key, g.owner_id, g.created_at,
       (SELECT COUNT(*) FROM dm_group_members mm WHERE mm.group_id = g.id) AS member_count
  FROM dm_groups g
  JOIN dm_group_members m ON m.group_id = g.id
 WHERE m.user_id = $1
 ORDER BY g.created_at DESC
`

type ListMyDMGroupsRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        *string            `json:"name"`
	IconKey     *string            `json:"icon_key"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	MemberCount int64              `json:"member_count"`
}

func (q *Queries) ListMyDMGroups(ctx context.Context, userID pgtype.UUID) ([]ListMyDMGroupsRow, error) {
	rows, err := q.db.Query(ctx, listMyDMGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMyDMGroupsRow{}
	for rows.Next() {
		var i ListMyDMGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IconKey,
			&i.OwnerID,
			&i.CreatedAt,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDMGroupMember = `-- name: RemoveDMGroupMember :exec
DELETE FROM dm_group_members WHERE group_id = $1 AND user_id = $2
`

type RemoveDMGroupMemberParams struct {
	GroupID pgtype.UUID `json:"group_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemoveDMGroupMember(ctx context.Context, arg RemoveDMGroupMemberParams) error {
	_, err := q.db.Exec(ctx, removeDMGroupMember, arg.GroupID, arg.UserID)
	return err
}

const transferDMGroup = `-- name: TransferDMGroup :exec
UPDATE dm_groups SET owner_id = $2 WHERE id = $1
`

type TransferDMGroupParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) TransferDMGroup(ctx context.Context, arg TransferDMGroupParams) error {
	_, err := q.db.Exec(ctx, transferDMGroup, arg.ID, arg.OwnerID)
	return err
}

const updateDMGroup = `-- name: UpdateDMGroup :one
UPDATE dm_groups
   SET name     = COALESCE($2, name),
       icon_key = COALESCE($3, icon_key)
 WHERE id = $1
RETURNING id, owner_id, name, icon_key, created_at
`

type UpdateDMGroupParams struct {
	ID      pgtype.UUID `json:"id"`
	Name    *string     `json:"name"`
	IconKey *string     `json:"icon_key"`
}

func (q *Queries) UpdateDMGroup(ctx context.Context, arg UpdateDMGroupParams) (DmGroup, error) {
	row := q.db.QueryRow(ctx, updateDMGroup, arg.ID, arg.Name, arg.IconKey)
	var i DmGroup
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
	)
	return i, err
}
