// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_change.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailChangeToken = `-- name: ConsumeEmailChangeToken :one
UPDATE email_change_tokens
   SET used_at = NOW()
 WHERE token_hash = $1 AND used_at IS NULL AND expires_at > NOW()
RETURNING id, user_id, new_email, token_hash, expires_at, used_at, created_at
`

func (q *Queries) ConsumeEmailChangeToken(ctx context.Context, tokenHash string) (EmailChangeToken, error) {
	row := q.db.QueryRow(ctx, consumeEmailChangeToken, tokenHash)
	var i EmailChangeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createEmailChangeToken = `-- name: CreateEmailChangeToken :one
INSERT INTO email_change_tokens (user_id, new_email, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, new_email, token_hash, expires_at, used_at, created_at
`

type CreateEmailChangeTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	NewEmail  string             `json:"new_email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateEmailChangeToken(ctx context.Context, arg CreateEmailChangeTokenParams) (EmailChangeToken, error) {
	row := q.db.QueryRow(ctx, createEmailChangeToken,
		arg.UserID,
		arg.NewEmail,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	var i EmailChangeToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.NewEmail,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidatePendingEmailChanges = `-- name: InvalidatePendingEmailChanges :exec
UPDATE email_change_tokens
   SET used_at = NOW()
 WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) InvalidatePendingEmailChanges(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, invalidatePendingEmailChanges, userID)
	return err
}

const updateUserEmail = `-- name: UpdateUserEmail :exec
UPDATE users SET email = $2 WHERE id = $1
`

type UpdateUserEmailParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
}

func (q *Queries) UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error {
	_, err := q.db.Exec(ctx, updateUserEmail, arg.ID, arg.Email)
	return err
}
