// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: emojis.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSpaceEmojis = `-- name: CountSpaceEmojis :one
SELECT COUNT(*) FROM custom_emojis WHERE space_id = $1 AND kind = $2
`

type CountSpaceEmojisParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Kind    string      `json:"kind"`
}

func (q *Queries) CountSpaceEmojis(ctx context.Context, arg CountSpaceEmojisParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSpaceEmojis, arg.SpaceID, arg.Kind)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCustomEmoji = `-- name: CreateCustomEmoji :one
INSERT INTO custom_emojis (space_id, name, file_key, animated, created_by, kind)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, space_id, name, file_key, animated, created_by, created_at, kind
`

type CreateCustomEmojiParams struct {
	SpaceID   pgtype.UUID `json:"space_id"`
	Name      string      `json:"name"`
	FileKey   string      `json:"file_key"`
	Animated  bool        `json:"animated"`
	CreatedBy pgtype.UUID `json:"created_by"`
	Kind      string      `json:"kind"`
}

func (q *Queries) CreateCustomEmoji(ctx context.Context, arg CreateCustomEmojiParams) (CustomEmoji, error) {
	row := q.db.QueryRow(ctx, createCustomEmoji,
		arg.SpaceID,
		arg.Name,
		arg.FileKey,
		arg.Animated,
		arg.CreatedBy,
		arg.Kind,
	)
	var i CustomEmoji
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.FileKey,
		&i.Animated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const deleteCustomEmoji = `-- name: DeleteCustomEmoji :exec
DELETE FROM custom_emojis WHERE id = $1
`

func (q *Queries) DeleteCustomEmoji(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteCustomEmoji, id)
	return err
}

const getCustomEmoji = `-- name: GetCustomEmoji :one
SELECT id, space_id, name, file_key, animated, created_by, created_at, kind FROM custom_emojis WHERE id = $1
`

func (q *Queries) GetCustomEmoji(ctx context.Context, id pgtype.UUID) (CustomEmoji, error) {
	row := q.db.QueryRow(ctx, getCustomEmoji, id)
	var i CustomEmoji
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.FileKey,
		&i.Animated,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.Kind,
	)
	return i, err
}

const listSpaceEmojis = `-- name: ListSpaceEmojis :many
SELECT id, space_id, name, file_key, animated, created_by, created_at, kind FROM custom_emojis WHERE space_id = $1 AND kind = $2 ORDER BY name
`

type ListSpaceEmojisParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Kind    string      `json:"kind"`
}

func (q *Queries) ListSpaceEmojis(ctx context.Context, arg ListSpaceEmojisParams) ([]CustomEmoji, error) {
	rows, err := q.db.Query(ctx, listSpaceEmojis, arg.SpaceID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomEmoji{}
	for rows.Next() {
		var i CustomEmoji
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.FileKey,
			&i.Animated,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEmojis = `-- name: ListUserEmojis :many
SELECT e.id, e.space_id, e.name, e.file_key, e.animated, e.created_by, e.created_at, e.kind FROM custom_emojis e
  JOIN members m ON m.space_id = e.space_id
 WHERE m.user_id = $1 AND e.kind = $2
 ORDER BY e.space_id, e.name
`

type ListUserEmojisParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Kind   string      `json:"kind"`
}

func (q *Queries) ListUserEmojis(ctx context.Context, arg ListUserEmojisParams) ([]CustomEmoji, error) {
	rows, err := q.db.Query(ctx, listUserEmojis, arg.UserID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CustomEmoji{}
	for rows.Next() {
		var i CustomEmoji
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.FileKey,
			&i.Animated,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
