// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (space_id, title, description, location, starts_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, space_id, title, description, location, starts_at, created_by, created_at
`

type CreateEventParams struct {
	SpaceID     pgtype.UUID        `json:"space_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Location    *string            `json:"location"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.SpaceID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartsAt,
		arg.CreatedBy,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, space_id, title, description, location, starts_at, created_by, created_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id pgtype.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartsAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getMyRsvp = `-- name: GetMyRsvp :one
SELECT status FROM event_rsvps WHERE event_id = $1 AND user_id = $2
`

type GetMyRsvpParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMyRsvp(ctx context.Context, arg GetMyRsvpParams) (string, error) {
	row := q.db.QueryRow(ctx, getMyRsvp, arg.EventID, arg.UserID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const listSpaceEvents = `-- name: ListSpaceEvents :many
SELECT id, space_id, title, description, location, starts_at, created_by, created_at FROM events WHERE space_id = $1 ORDER BY starts_at LIMIT 200
`

func (q *Queries) ListSpaceEvents(ctx context.Context, spaceID pgtype.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listSpaceEvents, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartsAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rsvpCounts = `-- name: RsvpCounts :many
SELECT status, COUNT(*) AS n FROM event_rsvps WHERE event_id = $1 GROUP BY status
`

type RsvpCountsRow struct {
	Status string `json:"status"`
	N      int64  `json:"n"`
}

func (q *Queries) RsvpCounts(ctx context.Context, eventID pgtype.UUID) ([]RsvpCountsRow, error) {
	rows, err := q.db.Query(ctx, rsvpCounts, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RsvpCountsRow{}
	for rows.Next() {
		var i RsvpCountsRow
		if err := rows.Scan(&i.Status, &i.N); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setRsvp = `-- name: SetRsvp :exec
INSERT INTO event_rsvps (event_id, user_id, status)
VALUES ($1, $2, $3)
ON CONFLICT (event_id, user_id)
DO UPDATE SET status = EXCLUDED.status, responded_at = NOW()
`

type SetRsvpParams struct {
	EventID pgtype.UUID `json:"event_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Status  string      `json:"status"`
}

func (q *Queries) SetRsvp(ctx context.Context, arg SetRsvpParams) error {
	_, err := q.db.Exec(ctx, setRsvp, arg.EventID, arg.UserID, arg.Status)
	return err
}
