// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createFile = `-- name: CreateFile :one
INSERT INTO files (owner_id, filename, size, mimetype, path, sha256, kind)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, owner_id, filename, size, mimetype, path, created_at, sha256, kind, scan_status
`

type CreateFileParams struct {
	OwnerID  pgtype.UUID `json:"owner_id"`
	Filename string      `json:"filename"`
	Size     int64       `json:"size"`
	Mimetype string      `json:"mimetype"`
	Path     string      `json:"path"`
	Sha256   string      `json:"sha256"`
	Kind     string      `json:"kind"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.OwnerID,
		arg.Filename,
		arg.Size,
		arg.Mimetype,
		arg.Path,
		arg.Sha256,
		arg.Kind,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.Size,
		&i.Mimetype,
		&i.Path,
		&i.CreatedAt,
		&i.Sha256,
		&i.Kind,
		&i.ScanStatus,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFile = `-- name: GetFile :one
SELECT id, owner_id, filename, size, mimetype, path, created_at, sha256, kind, scan_status FROM files WHERE id = $1
`

func (q *Queries) GetFile(ctx context.Context, id pgtype.UUID) (File, error) {
	row := q.db.QueryRow(ctx, getFile, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.Size,
		&i.Mimetype,
		&i.Path,
		&i.CreatedAt,
		&i.Sha256,
		&i.Kind,
		&i.ScanStatus,
	)
	return i, err
}

const getFileByOwnerSHA = `-- name: GetFileByOwnerSHA :one

SELECT id, owner_id, filename, size, mimetype, path, created_at, sha256, kind, scan_status FROM files
 WHERE owner_id = $1 AND sha256 = $2
`

type GetFileByOwnerSHAParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Sha256  string      `json:"sha256"`
}

func (q *Queries) GetFileByOwnerSHA(ctx context.Context, arg GetFileByOwnerSHAParams) (File, error) {
	row := q.db.QueryRow(ctx, getFileByOwnerSHA, arg.OwnerID, arg.Sha256)
	var i File
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Filename,
		&i.Size,
		&i.Mimetype,
		&i.Path,
		&i.CreatedAt,
		&i.Sha256,
		&i.Kind,
		&i.ScanStatus,
	)
	return i, err
}

const listOwnerFiles = `-- name: ListOwnerFiles :many
SELECT id, filename, size, mimetype, kind, created_at
  FROM files
 WHERE owner_id = $1
 ORDER BY created_at DESC
 LIMIT 200
`

type ListOwnerFilesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Filename  string             `json:"filename"`
	Size      int64              `json:"size"`
	Mimetype  string             `json:"mimetype"`
	Kind      string             `json:"kind"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOwnerFiles(ctx context.Context, ownerID pgtype.UUID) ([]ListOwnerFilesRow, error) {
	rows, err := q.db.Query(ctx, listOwnerFiles, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOwnerFilesRow{}
	for rows.Next() {
		var i ListOwnerFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Filename,
			&i.Size,
			&i.Mimetype,
			&i.Kind,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOwnerFilesByKind = `-- name: ListOwnerFilesByKind :many
SELECT id, owner_id, filename, size, mimetype, path, created_at, sha256, kind, scan_status FROM files
 WHERE owner_id = $1 AND kind = $2
 ORDER BY created_at DESC
`

type ListOwnerFilesByKindParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Kind    string      `json:"kind"`
}

func (q *Queries) ListOwnerFilesByKind(ctx context.Context, arg ListOwnerFilesByKindParams) ([]File, error) {
	rows, err := q.db.Query(ctx, listOwnerFilesByKind, arg.OwnerID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Filename,
			&i.Size,
			&i.Mimetype,
			&i.Path,
			&i.CreatedAt,
			&i.Sha256,
			&i.Kind,
			&i.ScanStatus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalOwnerStorage = `-- name: TotalOwnerStorage :one
SELECT COALESCE(SUM(size), 0)::bigint FROM files WHERE owner_id = $1
`

func (q *Queries) TotalOwnerStorage(ctx context.Context, ownerID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, totalOwnerStorage, ownerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const updateFileScanStatus = `-- name: UpdateFileScanStatus :exec

UPDATE files SET scan_status = $2 WHERE id = $1
`

type UpdateFileScanStatusParams struct {
	ID         pgtype.UUID `json:"id"`
	ScanStatus string      `json:"scan_status"`
}

func (q *Queries) UpdateFileScanStatus(ctx context.Context, arg UpdateFileScanStatusParams) error {
	_, err := q.db.Exec(ctx, updateFileScanStatus, arg.ID, arg.ScanStatus)
	return err
}
