// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: friends.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptFriendRequest = `-- name: AcceptFriendRequest :one
UPDATE friendships SET status = 'accepted'
 WHERE id = $1 AND addressee_id = $2 AND status = 'pending'
RETURNING id, requester_id, addressee_id, status, created_at
`

type AcceptFriendRequestParams struct {
	ID          pgtype.UUID `json:"id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, acceptFriendRequest, arg.ID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createBlock = `-- name: CreateBlock :exec
INSERT INTO blocks (blocker_id, blocked_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type CreateBlockParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.Exec(ctx, createBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const createFriendRequest = `-- name: CreateFriendRequest :one
INSERT INTO friendships (requester_id, addressee_id, status)
VALUES ($1, $2, 'pending')
RETURNING id, requester_id, addressee_id, status, created_at
`

type CreateFriendRequestParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, createFriendRequest, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM blocks WHERE blocker_id = $1 AND blocked_id = $2
`

type DeleteBlockParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.Exec(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const deleteFriendship = `-- name: DeleteFriendship :exec

DELETE FROM friendships
 WHERE id = $1 AND (requester_id = $2 OR addressee_id = $2)
`

type DeleteFriendshipParams struct {
	ID          pgtype.UUID `json:"id"`
	RequesterID pgtype.UUID `json:"requester_id"`
}

func (q *Queries) DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error {
	_, err := q.db.Exec(ctx, deleteFriendship, arg.ID, arg.RequesterID)
	return err
}

const deleteFriendshipByPair = `-- name: DeleteFriendshipByPair :exec
DELETE FROM friendships
 WHERE (requester_id = $1 AND addressee_id = $2)
    OR (requester_id = $2 AND addressee_id = $1)
`

type DeleteFriendshipByPairParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) DeleteFriendshipByPair(ctx context.Context, arg DeleteFriendshipByPairParams) error {
	_, err := q.db.Exec(ctx, deleteFriendshipByPair, arg.RequesterID, arg.AddresseeID)
	return err
}

const getFriendshipByID = `-- name: GetFriendshipByID :one
SELECT id, requester_id, addressee_id, status, created_at FROM friendships WHERE id = $1
`

func (q *Queries) GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByID, id)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFriendshipByPair = `-- name: GetFriendshipByPair :one

SELECT id, requester_id, addressee_id, status, created_at FROM friendships
 WHERE (requester_id = $1 AND addressee_id = $2)
    OR (requester_id = $2 AND addressee_id = $1)
`

type GetFriendshipByPairParams struct {
	RequesterID pgtype.UUID `json:"requester_id"`
	AddresseeID pgtype.UUID `json:"addressee_id"`
}

func (q *Queries) GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error) {
	row := q.db.QueryRow(ctx, getFriendshipByPair, arg.RequesterID, arg.AddresseeID)
	var i Friendship
	err := row.Scan(
		&i.ID,
		&i.RequesterID,
		&i.AddresseeID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const hasMutualFriend = `-- name: HasMutualFriend :one

WITH a_friends AS (
  SELECT CASE WHEN fa.requester_id = $1 THEN fa.addressee_id ELSE fa.requester_id END AS fid
    FROM friendships fa
   WHERE (fa.requester_id = $1 OR fa.addressee_id = $1) AND fa.status = 'accepted'
),
b_friends AS (
  SELECT CASE WHEN fb.requester_id = $2 THEN fb.addressee_id ELSE fb.requester_id END AS fid
    FROM friendships fb
   WHERE (fb.requester_id = $2 OR fb.addressee_id = $2) AND fb.status = 'accepted'
)
SELECT EXISTS (
  SELECT 1 FROM a_friends a JOIN b_friends b ON a.fid = b.fid
) AS mutual
`

type HasMutualFriendParams struct {
	RequesterID   pgtype.UUID `json:"requester_id"`
	RequesterID_2 pgtype.UUID `json:"requester_id_2"`
}

func (q *Queries) HasMutualFriend(ctx context.Context, arg HasMutualFriendParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMutualFriend, arg.RequesterID, arg.RequesterID_2)
	var mutual bool
	err := row.Scan(&mutual)
	return mutual, err
}

const isBlockedEitherWay = `-- name: IsBlockedEitherWay :one

SELECT EXISTS (
  SELECT 1 FROM blocks
   WHERE (blocker_id = $1 AND blocked_id = $2)
      OR (blocker_id = $2 AND blocked_id = $1)
) AS blocked
`

type IsBlockedEitherWayParams struct {
	BlockerID pgtype.UUID `json:"blocker_id"`
	BlockedID pgtype.UUID `json:"blocked_id"`
}

func (q *Queries) IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBlockedEitherWay, arg.BlockerID, arg.BlockedID)
	var blocked bool
	err := row.Scan(&blocked)
	return blocked, err
}

const listAcceptedFriends = `-- name: ListAcceptedFriends :many

SELECT u.id, u.username, u.avatar_key, f.created_at
  FROM friendships f
  JOIN users u ON u.id = CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END
 WHERE (f.requester_id = $1 OR f.addressee_id = $1) AND f.status = 'accepted'
 ORDER BY u.username
`

type ListAcceptedFriendsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	AvatarKey *string            `json:"avatar_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListAcceptedFriends(ctx context.Context, requesterID pgtype.UUID) ([]ListAcceptedFriendsRow, error) {
	rows, err := q.db.Query(ctx, listAcceptedFriends, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAcceptedFriendsRow{}
	for rows.Next() {
		var i ListAcceptedFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlocks = `-- name: ListBlocks :many
SELECT u.id, u.username, u.avatar_key, b.created_at
  FROM blocks b
  JOIN users u ON u.id = b.blocked_id
 WHERE b.blocker_id = $1
 ORDER BY u.username
`

type ListBlocksRow struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	AvatarKey *string            `json:"avatar_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListBlocks(ctx context.Context, blockerID pgtype.UUID) ([]ListBlocksRow, error) {
	rows, err := q.db.Query(ctx, listBlocks, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBlocksRow{}
	for rows.Next() {
		var i ListBlocksRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.AvatarKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncomingRequests = `-- name: ListIncomingRequests :many
SELECT f.id, u.id AS user_id, u.username, u.avatar_key, f.created_at
  FROM friendships f
  JOIN users u ON u.id = f.requester_id
 WHERE f.addressee_id = $1 AND f.status = 'pending'
 ORDER BY f.created_at DESC
`

type ListIncomingRequestsRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Username  string             `json:"username"`
	AvatarKey *string            `json:"avatar_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListIncomingRequests(ctx context.Context, addresseeID pgtype.UUID) ([]ListIncomingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listIncomingRequests, addresseeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIncomingRequestsRow{}
	for rows.Next() {
		var i ListIncomingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.AvatarKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMutualFriends = `-- name: ListMutualFriends :many

SELECT u.id, u.username, COALESCE(u.display_name, u.username) AS display_name, u.avatar_key
  FROM users u
 WHERE u.disabled = false
   AND u.id IN (
     SELECT CASE WHEN f.requester_id = $1 THEN f.addressee_id ELSE f.requester_id END
       FROM friendships f
      WHERE (f.requester_id = $1 OR f.addressee_id = $1) AND f.status = 'accepted'
   )
   AND u.id IN (
     SELECT CASE WHEN f.requester_id = $2 THEN f.addressee_id ELSE f.requester_id END
       FROM friendships f
      WHERE (f.requester_id = $2 OR f.addressee_id = $2) AND f.status = 'accepted'
   )
 ORDER BY display_name
`

type ListMutualFriendsParams struct {
	RequesterID   pgtype.UUID `json:"requester_id"`
	RequesterID_2 pgtype.UUID `json:"requester_id_2"`
}

type ListMutualFriendsRow struct {
	ID          pgtype.UUID `json:"id"`
	Username    string      `json:"username"`
	DisplayName string      `json:"display_name"`
	AvatarKey   *string     `json:"avatar_key"`
}

func (q *Queries) ListMutualFriends(ctx context.Context, arg ListMutualFriendsParams) ([]ListMutualFriendsRow, error) {
	rows, err := q.db.Query(ctx, listMutualFriends, arg.RequesterID, arg.RequesterID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMutualFriendsRow{}
	for rows.Next() {
		var i ListMutualFriendsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOutgoingRequests = `-- name: ListOutgoingRequests :many
SELECT f.id, u.id AS user_id, u.username, u.avatar_key, f.created_at
  FROM friendships f
  JOIN users u ON u.id = f.addressee_id
 WHERE f.requester_id = $1 AND f.status = 'pending'
 ORDER BY f.created_at DESC
`

type ListOutgoingRequestsRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Username  string             `json:"username"`
	AvatarKey *string            `json:"avatar_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListOutgoingRequests(ctx context.Context, requesterID pgtype.UUID) ([]ListOutgoingRequestsRow, error) {
	rows, err := q.db.Query(ctx, listOutgoingRequests, requesterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOutgoingRequestsRow{}
	for rows.Next() {
		var i ListOutgoingRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Username,
			&i.AvatarKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setWhoCanAdd = `-- name: SetWhoCanAdd :exec
UPDATE users SET who_can_add = $2 WHERE id = $1
`

type SetWhoCanAddParams struct {
	ID        pgtype.UUID `json:"id"`
	WhoCanAdd string      `json:"who_can_add"`
}

func (q *Queries) SetWhoCanAdd(ctx context.Context, arg SetWhoCanAddParams) error {
	_, err := q.db.Exec(ctx, setWhoCanAdd, arg.ID, arg.WhoCanAdd)
	return err
}
