// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: games.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGame = `-- name: GetGame :one
SELECT id, name, cover_key, status, submitted_by, reviewed_by, reject_reason, aliases, created_at FROM games WHERE id = $1
`

func (q *Queries) GetGame(ctx context.Context, id pgtype.UUID) (Game, error) {
	row := q.db.QueryRow(ctx, getGame, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoverKey,
		&i.Status,
		&i.SubmittedBy,
		&i.ReviewedBy,
		&i.RejectReason,
		&i.Aliases,
		&i.CreatedAt,
	)
	return i, err
}

const listApprovedGames = `-- name: ListApprovedGames :many

SELECT id, name, cover_key, status, submitted_by, reviewed_by, reject_reason, aliases, created_at FROM games
 WHERE status = 'approved'
   AND ($1::text = '' OR name ILIKE '%' || $1 || '%')
 ORDER BY name
 LIMIT $2
`

type ListApprovedGamesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListApprovedGames(ctx context.Context, arg ListApprovedGamesParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listApprovedGames, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoverKey,
			&i.Status,
			&i.SubmittedBy,
			&i.ReviewedBy,
			&i.RejectReason,
			&i.Aliases,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGamesByStatus = `-- name: ListGamesByStatus :many

SELECT id, name, cover_key, status, submitted_by, reviewed_by, reject_reason, aliases, created_at FROM games WHERE status = $1 ORDER BY created_at LIMIT $2
`

type ListGamesByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListGamesByStatus(ctx context.Context, arg ListGamesByStatusParams) ([]Game, error) {
	rows, err := q.db.Query(ctx, listGamesByStatus, arg.Status, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Game{}
	for rows.Next() {
		var i Game
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CoverKey,
			&i.Status,
			&i.SubmittedBy,
			&i.ReviewedBy,
			&i.RejectReason,
			&i.Aliases,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewGame = `-- name: ReviewGame :one

UPDATE games
   SET status = $2, reviewed_by = $3, reject_reason = $4
 WHERE id = $1
RETURNING id, name, cover_key, status, submitted_by, reviewed_by, reject_reason, aliases, created_at
`

type ReviewGameParams struct {
	ID           pgtype.UUID `json:"id"`
	Status       string      `json:"status"`
	ReviewedBy   pgtype.UUID `json:"reviewed_by"`
	RejectReason *string     `json:"reject_reason"`
}

func (q *Queries) ReviewGame(ctx context.Context, arg ReviewGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, reviewGame,
		arg.ID,
		arg.Status,
		arg.ReviewedBy,
		arg.RejectReason,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoverKey,
		&i.Status,
		&i.SubmittedBy,
		&i.ReviewedBy,
		&i.RejectReason,
		&i.Aliases,
		&i.CreatedAt,
	)
	return i, err
}

const submitGame = `-- name: SubmitGame :one
INSERT INTO games (name, cover_key, submitted_by, aliases)
VALUES ($1, $2, $3, $4)
RETURNING id, name, cover_key, status, submitted_by, reviewed_by, reject_reason, aliases, created_at
`

type SubmitGameParams struct {
	Name        string      `json:"name"`
	CoverKey    *string     `json:"cover_key"`
	SubmittedBy pgtype.UUID `json:"submitted_by"`
	Aliases     []string    `json:"aliases"`
}

func (q *Queries) SubmitGame(ctx context.Context, arg SubmitGameParams) (Game, error) {
	row := q.db.QueryRow(ctx, submitGame,
		arg.Name,
		arg.CoverKey,
		arg.SubmittedBy,
		arg.Aliases,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CoverKey,
		&i.Status,
		&i.SubmittedBy,
		&i.ReviewedBy,
		&i.RejectReason,
		&i.Aliases,
		&i.CreatedAt,
	)
	return i, err
}
