// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (space_id, creator_id, code, max_uses, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, space_id, creator_id, code, max_uses, uses, expires_at, created_at
`

type CreateInviteParams struct {
	SpaceID   pgtype.UUID        `json:"space_id"`
	CreatorID pgtype.UUID        `json:"creator_id"`
	Code      string             `json:"code"`
	MaxUses   *int32             `json:"max_uses"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.SpaceID,
		arg.CreatorID,
		arg.Code,
		arg.MaxUses,
		arg.ExpiresAt,
	)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CreatorID,
		&i.Code,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredInvites = `-- name: DeleteExpiredInvites :exec
DELETE FROM invites
 WHERE (expires_at IS NOT NULL AND expires_at < NOW())
    OR (max_uses IS NOT NULL AND COALESCE(uses, 0) >= max_uses)
`

func (q *Queries) DeleteExpiredInvites(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredInvites)
	return err
}

const deleteInvite = `-- name: DeleteInvite :exec
DELETE FROM invites WHERE id = $1
`

func (q *Queries) DeleteInvite(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvite, id)
	return err
}

const deleteInviteByCode = `-- name: DeleteInviteByCode :exec
DELETE FROM invites WHERE code = $1
`

func (q *Queries) DeleteInviteByCode(ctx context.Context, code string) error {
	_, err := q.db.Exec(ctx, deleteInviteByCode, code)
	return err
}

const findReusableInvite = `-- name: FindReusableInvite :one

SELECT id, space_id, creator_id, code, max_uses, uses, expires_at, created_at FROM invites
 WHERE space_id = $1
   AND max_uses IS NOT DISTINCT FROM $2::int
   AND (expires_at IS NULL OR expires_at > NOW())
   AND (max_uses IS NULL OR COALESCE(uses, 0) < max_uses)
 ORDER BY created_at DESC
 LIMIT 1
`

type FindReusableInviteParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	MaxUses *int32      `json:"max_uses"`
}

func (q *Queries) FindReusableInvite(ctx context.Context, arg FindReusableInviteParams) (Invite, error) {
	row := q.db.QueryRow(ctx, findReusableInvite, arg.SpaceID, arg.MaxUses)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CreatorID,
		&i.Code,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getInviteByCode = `-- name: GetInviteByCode :one
SELECT id, space_id, creator_id, code, max_uses, uses, expires_at, created_at FROM invites WHERE code = $1
`

func (q *Queries) GetInviteByCode(ctx context.Context, code string) (Invite, error) {
	row := q.db.QueryRow(ctx, getInviteByCode, code)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CreatorID,
		&i.Code,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const incrementInviteUses = `-- name: IncrementInviteUses :one
UPDATE invites SET uses = COALESCE(uses, 0) + 1
 WHERE id = $1
RETURNING id, space_id, creator_id, code, max_uses, uses, expires_at, created_at
`

func (q *Queries) IncrementInviteUses(ctx context.Context, id pgtype.UUID) (Invite, error) {
	row := q.db.QueryRow(ctx, incrementInviteUses, id)
	var i Invite
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.CreatorID,
		&i.Code,
		&i.MaxUses,
		&i.Uses,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceInvites = `-- name: ListSpaceInvites :many
SELECT id, space_id, creator_id, code, max_uses, uses, expires_at, created_at FROM invites WHERE space_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpaceInvites(ctx context.Context, spaceID pgtype.UUID) ([]Invite, error) {
	rows, err := q.db.Query(ctx, listSpaceInvites, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invite{}
	for rows.Next() {
		var i Invite
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.CreatorID,
			&i.Code,
			&i.MaxUses,
			&i.Uses,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
