// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: joingate.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJoinRequest = `-- name: CreateJoinRequest :one
INSERT INTO join_requests (space_id, user_id, answers)
VALUES ($1, $2, $3)
RETURNING id, space_id, user_id, answers, status, reviewed_by, reviewed_at, created_at
`

type CreateJoinRequestParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	UserID  pgtype.UUID `json:"user_id"`
	Answers []byte      `json:"answers"`
}

func (q *Queries) CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, createJoinRequest, arg.SpaceID, arg.UserID, arg.Answers)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Answers,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getJoinForm = `-- name: GetJoinForm :one
SELECT space_id, enabled, questions, auto_role_id, updated_at, min_karma FROM join_forms WHERE space_id = $1
`

func (q *Queries) GetJoinForm(ctx context.Context, spaceID pgtype.UUID) (JoinForm, error) {
	row := q.db.QueryRow(ctx, getJoinForm, spaceID)
	var i JoinForm
	err := row.Scan(
		&i.SpaceID,
		&i.Enabled,
		&i.Questions,
		&i.AutoRoleID,
		&i.UpdatedAt,
		&i.MinKarma,
	)
	return i, err
}

const getJoinRequest = `-- name: GetJoinRequest :one
SELECT id, space_id, user_id, answers, status, reviewed_by, reviewed_at, created_at FROM join_requests WHERE id = $1
`

func (q *Queries) GetJoinRequest(ctx context.Context, id pgtype.UUID) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, getJoinRequest, id)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Answers,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listJoinRequests = `-- name: ListJoinRequests :many
SELECT jr.id, jr.space_id, jr.user_id, jr.answers, jr.status, jr.reviewed_by, jr.reviewed_at, jr.created_at, u.username, u.display_name, u.avatar_key
  FROM join_requests jr
  JOIN users u ON u.id = jr.user_id
 WHERE jr.space_id = $1 AND jr.status = $2
 ORDER BY jr.created_at ASC
 LIMIT $3 OFFSET $4
`

type ListJoinRequestsParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Status  string      `json:"status"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListJoinRequestsRow struct {
	ID          pgtype.UUID        `json:"id"`
	SpaceID     pgtype.UUID        `json:"space_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Answers     []byte             `json:"answers"`
	Status      string             `json:"status"`
	ReviewedBy  pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt  pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Username    string             `json:"username"`
	DisplayName *string            `json:"display_name"`
	AvatarKey   *string            `json:"avatar_key"`
}

func (q *Queries) ListJoinRequests(ctx context.Context, arg ListJoinRequestsParams) ([]ListJoinRequestsRow, error) {
	rows, err := q.db.Query(ctx, listJoinRequests,
		arg.SpaceID,
		arg.Status,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListJoinRequestsRow{}
	for rows.Next() {
		var i ListJoinRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.Answers,
			&i.Status,
			&i.ReviewedBy,
			&i.ReviewedAt,
			&i.CreatedAt,
			&i.Username,
			&i.DisplayName,
			&i.AvatarKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reviewJoinRequest = `-- name: ReviewJoinRequest :one
UPDATE join_requests
   SET status = $2, reviewed_by = $3, reviewed_at = NOW()
 WHERE id = $1 AND status = 'pending'
RETURNING id, space_id, user_id, answers, status, reviewed_by, reviewed_at, created_at
`

type ReviewJoinRequestParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     string      `json:"status"`
	ReviewedBy pgtype.UUID `json:"reviewed_by"`
}

func (q *Queries) ReviewJoinRequest(ctx context.Context, arg ReviewJoinRequestParams) (JoinRequest, error) {
	row := q.db.QueryRow(ctx, reviewJoinRequest, arg.ID, arg.Status, arg.ReviewedBy)
	var i JoinRequest
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Answers,
		&i.Status,
		&i.ReviewedBy,
		&i.ReviewedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertJoinForm = `-- name: UpsertJoinForm :one
INSERT INTO join_forms (space_id, enabled, questions, auto_role_id, min_karma, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (space_id)
DO UPDATE SET enabled      = EXCLUDED.enabled,
              questions    = EXCLUDED.questions,
              auto_role_id = EXCLUDED.auto_role_id,
              min_karma    = EXCLUDED.min_karma,
              updated_at   = NOW()
RETURNING space_id, enabled, questions, auto_role_id, updated_at, min_karma
`

type UpsertJoinFormParams struct {
	SpaceID    pgtype.UUID `json:"space_id"`
	Enabled    bool        `json:"enabled"`
	Questions  []byte      `json:"questions"`
	AutoRoleID pgtype.UUID `json:"auto_role_id"`
	MinKarma   int32       `json:"min_karma"`
}

func (q *Queries) UpsertJoinForm(ctx context.Context, arg UpsertJoinFormParams) (JoinForm, error) {
	row := q.db.QueryRow(ctx, upsertJoinForm,
		arg.SpaceID,
		arg.Enabled,
		arg.Questions,
		arg.AutoRoleID,
		arg.MinKarma,
	)
	var i JoinForm
	err := row.Scan(
		&i.SpaceID,
		&i.Enabled,
		&i.Questions,
		&i.AutoRoleID,
		&i.UpdatedAt,
		&i.MinKarma,
	)
	return i, err
}
