// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: karma.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addKarma = `-- name: AddKarma :one
INSERT INTO karma (user_id, space_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, space_id)
DO UPDATE SET score = karma.score + EXCLUDED.score, updated_at = NOW()
RETURNING score
`

type AddKarmaParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	SpaceID pgtype.UUID `json:"space_id"`
	Score   int32       `json:"score"`
}

func (q *Queries) AddKarma(ctx context.Context, arg AddKarmaParams) (int32, error) {
	row := q.db.QueryRow(ctx, addKarma, arg.UserID, arg.SpaceID, arg.Score)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const countKarmaEventsBySourceSince = `-- name: CountKarmaEventsBySourceSince :one
SELECT COUNT(*) FROM karma_events
 WHERE source_user = $1 AND created_at >= $2
`

type CountKarmaEventsBySourceSinceParams struct {
	SourceUser pgtype.UUID        `json:"source_user"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountKarmaEventsBySourceSince(ctx context.Context, arg CountKarmaEventsBySourceSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countKarmaEventsBySourceSince, arg.SourceUser, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getKarma = `-- name: GetKarma :one
SELECT score FROM karma WHERE user_id = $1 AND space_id = $2
`

type GetKarmaParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	SpaceID pgtype.UUID `json:"space_id"`
}

func (q *Queries) GetKarma(ctx context.Context, arg GetKarmaParams) (int32, error) {
	row := q.db.QueryRow(ctx, getKarma, arg.UserID, arg.SpaceID)
	var score int32
	err := row.Scan(&score)
	return score, err
}

const insertKarmaEvent = `-- name: InsertKarmaEvent :one
INSERT INTO karma_events (space_id, target_user, source_user, delta, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type InsertKarmaEventParams struct {
	SpaceID    pgtype.UUID `json:"space_id"`
	TargetUser pgtype.UUID `json:"target_user"`
	SourceUser pgtype.UUID `json:"source_user"`
	Delta      int32       `json:"delta"`
	Reason     string      `json:"reason"`
}

func (q *Queries) InsertKarmaEvent(ctx context.Context, arg InsertKarmaEventParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertKarmaEvent,
		arg.SpaceID,
		arg.TargetUser,
		arg.SourceUser,
		arg.Delta,
		arg.Reason,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listSpaceKarma = `-- name: ListSpaceKarma :many
SELECT user_id, score FROM karma
 WHERE space_id = $1
 ORDER BY score DESC, user_id
 LIMIT $2 OFFSET $3
`

type ListSpaceKarmaParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListSpaceKarmaRow struct {
	UserID pgtype.UUID `json:"user_id"`
	Score  int32       `json:"score"`
}

func (q *Queries) ListSpaceKarma(ctx context.Context, arg ListSpaceKarmaParams) ([]ListSpaceKarmaRow, error) {
	rows, err := q.db.Query(ctx, listSpaceKarma, arg.SpaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpaceKarmaRow{}
	for rows.Next() {
		var i ListSpaceKarmaRow
		if err := rows.Scan(&i.UserID, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumUserKarma = `-- name: SumUserKarma :one
SELECT COALESCE(SUM(score), 0)::bigint FROM karma WHERE user_id = $1
`

func (q *Queries) SumUserKarma(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumUserKarma, userID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
