// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
)

const maliciousURLHashes = `-- name: MaliciousURLHashes :many

SELECT url_hash, threat FROM malicious_urls
 WHERE url_hash = ANY($1::text[])
`

type MaliciousURLHashesRow struct {
	UrlHash string  `json:"url_hash"`
	Threat  *string `json:"threat"`
}

func (q *Queries) MaliciousURLHashes(ctx context.Context, hashes []string) ([]MaliciousURLHashesRow, error) {
	rows, err := q.db.Query(ctx, maliciousURLHashes, hashes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaliciousURLHashesRow{}
	for rows.Next() {
		var i MaliciousURLHashesRow
		if err := rows.Scan(&i.UrlHash, &i.Threat); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
