// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: member_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignMemberRole = `-- name: AssignMemberRole :exec

INSERT INTO member_roles (member_id, role_id, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (member_id, role_id) DO UPDATE SET expires_at = EXCLUDED.expires_at
`

type AssignMemberRoleParams struct {
	MemberID  pgtype.UUID        `json:"member_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) AssignMemberRole(ctx context.Context, arg AssignMemberRoleParams) error {
	_, err := q.db.Exec(ctx, assignMemberRole, arg.MemberID, arg.RoleID, arg.ExpiresAt)
	return err
}

const deleteExpiredMemberRoles = `-- name: DeleteExpiredMemberRoles :execrows
DELETE FROM member_roles WHERE expires_at IS NOT NULL AND expires_at < now()
`

func (q *Queries) DeleteExpiredMemberRoles(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredMemberRoles)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const hasMemberRole = `-- name: HasMemberRole :one
SELECT EXISTS (
  SELECT 1 FROM member_roles WHERE member_id = $1 AND role_id = $2
) AS present
`

type HasMemberRoleParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

func (q *Queries) HasMemberRole(ctx context.Context, arg HasMemberRoleParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasMemberRole, arg.MemberID, arg.RoleID)
	var present bool
	err := row.Scan(&present)
	return present, err
}

const removeMemberRole = `-- name: RemoveMemberRole :exec
DELETE FROM member_roles WHERE member_id = $1 AND role_id = $2
`

type RemoveMemberRoleParams struct {
	MemberID pgtype.UUID `json:"member_id"`
	RoleID   pgtype.UUID `json:"role_id"`
}

func (q *Queries) RemoveMemberRole(ctx context.Context, arg RemoveMemberRoleParams) error {
	_, err := q.db.Exec(ctx, removeMemberRole, arg.MemberID, arg.RoleID)
	return err
}
