// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: members.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMember = `-- name: CreateMember :one
INSERT INTO members (space_id, user_id, nickname)
VALUES ($1, $2, $3)
RETURNING id, space_id, user_id, nickname, joined_at, avatar_key, bio
`

type CreateMemberParams struct {
	SpaceID  pgtype.UUID `json:"space_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Nickname *string     `json:"nickname"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error) {
	row := q.db.QueryRow(ctx, createMember, arg.SpaceID, arg.UserID, arg.Nickname)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.AvatarKey,
		&i.Bio,
	)
	return i, err
}

const deleteMember = `-- name: DeleteMember :exec
DELETE FROM members WHERE id = $1
`

func (q *Queries) DeleteMember(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMember, id)
	return err
}

const getMember = `-- name: GetMember :one
SELECT id, space_id, user_id, nickname, joined_at, avatar_key, bio FROM members WHERE id = $1
`

func (q *Queries) GetMember(ctx context.Context, id pgtype.UUID) (Member, error) {
	row := q.db.QueryRow(ctx, getMember, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.AvatarKey,
		&i.Bio,
	)
	return i, err
}

const getMemberByUser = `-- name: GetMemberByUser :one
SELECT id, space_id, user_id, nickname, joined_at, avatar_key, bio FROM members
 WHERE space_id = $1 AND user_id = $2
`

type GetMemberByUserParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	UserID  pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMemberByUser(ctx context.Context, arg GetMemberByUserParams) (Member, error) {
	row := q.db.QueryRow(ctx, getMemberByUser, arg.SpaceID, arg.UserID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.AvatarKey,
		&i.Bio,
	)
	return i, err
}

const listMutualSpaces = `-- name: ListMutualSpaces :many

SELECT s.id, s.name, s.icon_key
  FROM spaces s
 WHERE s.id IN (SELECT m.space_id FROM members m WHERE m.user_id = $1)
   AND s.id IN (SELECT m.space_id FROM members m WHERE m.user_id = $2)
 ORDER BY s.name
`

type ListMutualSpacesParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	UserID_2 pgtype.UUID `json:"user_id_2"`
}

type ListMutualSpacesRow struct {
	ID      pgtype.UUID `json:"id"`
	Name    string      `json:"name"`
	IconKey *string     `json:"icon_key"`
}

func (q *Queries) ListMutualSpaces(ctx context.Context, arg ListMutualSpacesParams) ([]ListMutualSpacesRow, error) {
	rows, err := q.db.Query(ctx, listMutualSpaces, arg.UserID, arg.UserID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMutualSpacesRow{}
	for rows.Next() {
		var i ListMutualSpacesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.IconKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceMembers = `-- name: ListSpaceMembers :many

SELECT m.id, m.space_id, m.user_id, m.nickname, m.joined_at,
       u.username,
       COALESCE(m.avatar_key, u.avatar_key) AS avatar_key,
       m.bio,
       u.badges,
       (SELECT r.color FROM member_roles mr JOIN roles r ON r.id = mr.role_id
         WHERE mr.member_id = m.id AND r.color IS NOT NULL AND r.is_everyone IS NOT TRUE
         ORDER BY r.position DESC LIMIT 1) AS role_color,
       (SELECT r.icon_emoji FROM member_roles mr JOIN roles r ON r.id = mr.role_id
         WHERE mr.member_id = m.id AND r.icon_emoji IS NOT NULL AND r.is_everyone IS NOT TRUE
         ORDER BY r.position DESC LIMIT 1) AS role_icon,

       COALESCE((SELECT r.name FROM member_roles mr JOIN roles r ON r.id = mr.role_id
         WHERE mr.member_id = m.id AND r.hoist IS TRUE AND r.is_everyone IS NOT TRUE
         ORDER BY r.position DESC LIMIT 1), '')::text AS hoist_role,
       COALESCE((SELECT r.position FROM member_roles mr JOIN roles r ON r.id = mr.role_id
         WHERE mr.member_id = m.id AND r.hoist IS TRUE AND r.is_everyone IS NOT TRUE
         ORDER BY r.position DESC LIMIT 1), 0)::int AS hoist_position
  FROM members m
  JOIN users u ON u.id = m.user_id
 WHERE m.space_id = $1
 ORDER BY m.joined_at
`

type ListSpaceMembersRow struct {
	ID            pgtype.UUID        `json:"id"`
	SpaceID       pgtype.UUID        `json:"space_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	Nickname      *string            `json:"nickname"`
	JoinedAt      pgtype.Timestamptz `json:"joined_at"`
	Username      string             `json:"username"`
	AvatarKey     *string            `json:"avatar_key"`
	Bio           *string            `json:"bio"`
	Badges        []string           `json:"badges"`
	RoleColor     *string            `json:"role_color"`
	RoleIcon      *string            `json:"role_icon"`
	HoistRole     string             `json:"hoist_role"`
	HoistPosition int32              `json:"hoist_position"`
}

func (q *Queries) ListSpaceMembers(ctx context.Context, spaceID pgtype.UUID) ([]ListSpaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listSpaceMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpaceMembersRow{}
	for rows.Next() {
		var i ListSpaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.UserID,
			&i.Nickname,
			&i.JoinedAt,
			&i.Username,
			&i.AvatarKey,
			&i.Bio,
			&i.Badges,
			&i.RoleColor,
			&i.RoleIcon,
			&i.HoistRole,
			&i.HoistPosition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemberNickname = `-- name: UpdateMemberNickname :one
UPDATE members SET nickname = $2 WHERE id = $1 RETURNING id, space_id, user_id, nickname, joined_at, avatar_key, bio
`

type UpdateMemberNicknameParams struct {
	ID       pgtype.UUID `json:"id"`
	Nickname *string     `json:"nickname"`
}

func (q *Queries) UpdateMemberNickname(ctx context.Context, arg UpdateMemberNicknameParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberNickname, arg.ID, arg.Nickname)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.AvatarKey,
		&i.Bio,
	)
	return i, err
}

const updateMemberSpaceProfile = `-- name: UpdateMemberSpaceProfile :one
UPDATE members
   SET nickname   = $3,
       avatar_key = $4,
       bio        = $5
 WHERE space_id = $1 AND user_id = $2
RETURNING id, space_id, user_id, nickname, joined_at, avatar_key, bio
`

type UpdateMemberSpaceProfileParams struct {
	SpaceID   pgtype.UUID `json:"space_id"`
	UserID    pgtype.UUID `json:"user_id"`
	Nickname  *string     `json:"nickname"`
	AvatarKey *string     `json:"avatar_key"`
	Bio       *string     `json:"bio"`
}

func (q *Queries) UpdateMemberSpaceProfile(ctx context.Context, arg UpdateMemberSpaceProfileParams) (Member, error) {
	row := q.db.QueryRow(ctx, updateMemberSpaceProfile,
		arg.SpaceID,
		arg.UserID,
		arg.Nickname,
		arg.AvatarKey,
		arg.Bio,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.UserID,
		&i.Nickname,
		&i.JoinedAt,
		&i.AvatarKey,
		&i.Bio,
	)
	return i, err
}
