// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_follows.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const followMessage = `-- name: FollowMessage :exec
INSERT INTO message_follows (user_id, channel_id, archive_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type FollowMessageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
}

func (q *Queries) FollowMessage(ctx context.Context, arg FollowMessageParams) error {
	_, err := q.db.Exec(ctx, followMessage, arg.UserID, arg.ChannelID, arg.ArchiveID)
	return err
}

const isFollowingMessage = `-- name: IsFollowingMessage :one
SELECT EXISTS (
  SELECT 1 FROM message_follows
   WHERE user_id = $1 AND channel_id = $2 AND archive_id = $3
) AS following
`

type IsFollowingMessageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
}

func (q *Queries) IsFollowingMessage(ctx context.Context, arg IsFollowingMessageParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowingMessage, arg.UserID, arg.ChannelID, arg.ArchiveID)
	var following bool
	err := row.Scan(&following)
	return following, err
}

const listMessageFollowers = `-- name: ListMessageFollowers :many

SELECT user_id FROM message_follows
 WHERE channel_id = $1 AND archive_id = $2
`

type ListMessageFollowersParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
}

func (q *Queries) ListMessageFollowers(ctx context.Context, arg ListMessageFollowersParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMessageFollowers, arg.ChannelID, arg.ArchiveID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowMessage = `-- name: UnfollowMessage :exec
DELETE FROM message_follows
 WHERE user_id = $1 AND channel_id = $2 AND archive_id = $3
`

type UnfollowMessageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
}

func (q *Queries) UnfollowMessage(ctx context.Context, arg UnfollowMessageParams) error {
	_, err := q.db.Exec(ctx, unfollowMessage, arg.UserID, arg.ChannelID, arg.ArchiveID)
	return err
}
