// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mod_actions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createModAction = `-- name: CreateModAction :one
INSERT INTO mod_actions (space_id, target_user, moderator_id, action, reason, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, space_id, target_user, moderator_id, action, reason, expires_at, active, created_at
`

type CreateModActionParams struct {
	SpaceID     pgtype.UUID        `json:"space_id"`
	TargetUser  pgtype.UUID        `json:"target_user"`
	ModeratorID pgtype.UUID        `json:"moderator_id"`
	Action      string             `json:"action"`
	Reason      *string            `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateModAction(ctx context.Context, arg CreateModActionParams) (ModAction, error) {
	row := q.db.QueryRow(ctx, createModAction,
		arg.SpaceID,
		arg.TargetUser,
		arg.ModeratorID,
		arg.Action,
		arg.Reason,
		arg.ExpiresAt,
	)
	var i ModAction
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.TargetUser,
		&i.ModeratorID,
		&i.Action,
		&i.Reason,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateExpiredTimeouts = `-- name: DeactivateExpiredTimeouts :exec

UPDATE mod_actions SET active = FALSE
 WHERE action = 'timeout' AND active = TRUE
   AND expires_at IS NOT NULL AND expires_at <= NOW()
`

func (q *Queries) DeactivateExpiredTimeouts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deactivateExpiredTimeouts)
	return err
}

const getActiveTimeout = `-- name: GetActiveTimeout :one

SELECT id, space_id, target_user, moderator_id, action, reason, expires_at, active, created_at FROM mod_actions
 WHERE space_id = $1 AND target_user = $2 AND action = 'timeout' AND active = TRUE
   AND (expires_at IS NULL OR expires_at > NOW())
 ORDER BY created_at DESC
 LIMIT 1
`

type GetActiveTimeoutParams struct {
	SpaceID    pgtype.UUID `json:"space_id"`
	TargetUser pgtype.UUID `json:"target_user"`
}

func (q *Queries) GetActiveTimeout(ctx context.Context, arg GetActiveTimeoutParams) (ModAction, error) {
	row := q.db.QueryRow(ctx, getActiveTimeout, arg.SpaceID, arg.TargetUser)
	var i ModAction
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.TargetUser,
		&i.ModeratorID,
		&i.Action,
		&i.Reason,
		&i.ExpiresAt,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceModActions = `-- name: ListSpaceModActions :many

SELECT id, space_id, target_user, moderator_id, action, reason, expires_at, active, created_at FROM mod_actions
 WHERE space_id = $1
 ORDER BY created_at DESC
 LIMIT $2
`

type ListSpaceModActionsParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListSpaceModActions(ctx context.Context, arg ListSpaceModActionsParams) ([]ModAction, error) {
	rows, err := q.db.Query(ctx, listSpaceModActions, arg.SpaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModAction{}
	for rows.Next() {
		var i ModAction
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.TargetUser,
			&i.ModeratorID,
			&i.Action,
			&i.Reason,
			&i.ExpiresAt,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeTimeout = `-- name: RevokeTimeout :exec

UPDATE mod_actions SET active = FALSE
 WHERE space_id = $1 AND target_user = $2 AND action = 'timeout' AND active = TRUE
`

type RevokeTimeoutParams struct {
	SpaceID    pgtype.UUID `json:"space_id"`
	TargetUser pgtype.UUID `json:"target_user"`
}

func (q *Queries) RevokeTimeout(ctx context.Context, arg RevokeTimeoutParams) error {
	_, err := q.db.Exec(ctx, revokeTimeout, arg.SpaceID, arg.TargetUser)
	return err
}
