// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type RiverJobState string

const (
	RiverJobStateAvailable RiverJobState = "available"
	RiverJobStateCancelled RiverJobState = "cancelled"
	RiverJobStateCompleted RiverJobState = "completed"
	RiverJobStateDiscarded RiverJobState = "discarded"
	RiverJobStatePending   RiverJobState = "pending"
	RiverJobStateRetryable RiverJobState = "retryable"
	RiverJobStateRunning   RiverJobState = "running"
	RiverJobStateScheduled RiverJobState = "scheduled"
)

func (e *RiverJobState) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiverJobState(s)
	case string:
		*e = RiverJobState(s)
	default:
		return fmt.Errorf("unsupported scan type for RiverJobState: %T", src)
	}
	return nil
}

type NullRiverJobState struct {
	RiverJobState RiverJobState `json:"river_job_state"`
	Valid         bool          `json:"valid"` // Valid is true if RiverJobState is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiverJobState) Scan(value interface{}) error {
	if value == nil {
		ns.RiverJobState, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiverJobState.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiverJobState) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiverJobState), nil
}

type ApiToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	Prefix     string             `json:"prefix"`
	Scopes     []string           `json:"scopes"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLog struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	ActorID   pgtype.UUID        `json:"actor_id"`
	Action    string             `json:"action"`
	TargetID  pgtype.UUID        `json:"target_id"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Ban struct {
	ID          pgtype.UUID        `json:"id"`
	SpaceID     pgtype.UUID        `json:"space_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ModeratorID pgtype.UUID        `json:"moderator_id"`
	Reason      *string            `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type BannedIdentifier struct {
	ID        pgtype.UUID        `json:"id"`
	Kind      string             `json:"kind"`
	Value     string             `json:"value"`
	Reason    *string            `json:"reason"`
	BannedBy  pgtype.UUID        `json:"banned_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Block struct {
	BlockerID pgtype.UUID        `json:"blocker_id"`
	BlockedID pgtype.UUID        `json:"blocked_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Bot struct {
	ID           pgtype.UUID        `json:"id"`
	SpaceID      pgtype.UUID        `json:"space_id"`
	Name         string             `json:"name"`
	ComponentJid string             `json:"component_jid"`
	SecretHash   string             `json:"secret_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Category struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	Name      string             `json:"name"`
	Position  int32              `json:"position"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Channel struct {
	ID              pgtype.UUID        `json:"id"`
	SpaceID         pgtype.UUID        `json:"space_id"`
	Name            string             `json:"name"`
	Topic           *string            `json:"topic"`
	Type            *string            `json:"type"`
	Position        *int32             `json:"position"`
	IsPrivate       *bool              `json:"is_private"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Locked          bool               `json:"locked"`
	LockedBy        pgtype.UUID        `json:"locked_by"`
	LockedAt        pgtype.Timestamptz `json:"locked_at"`
	CategoryID      pgtype.UUID        `json:"category_id"`
	SlowmodeSeconds int32              `json:"slowmode_seconds"`
	Nsfw            bool               `json:"nsfw"`
	ReadOnly        bool               `json:"read_only"`
	IconEmoji       *string            `json:"icon_emoji"`
}

type ChannelOverwrite struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	RoleID    pgtype.UUID `json:"role_id"`
	Allow     *int64      `json:"allow"`
	Deny      *int64      `json:"deny"`
	MemberID  pgtype.UUID `json:"member_id"`
}

type ChannelReadState struct {
	UserID            pgtype.UUID        `json:"user_id"`
	ChannelID         pgtype.UUID        `json:"channel_id"`
	LastReadSortID    int64              `json:"last_read_sort_id"`
	LastReadArchiveID string             `json:"last_read_archive_id"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type CustomEmoji struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	Name      string             `json:"name"`
	FileKey   string             `json:"file_key"`
	Animated  bool               `json:"animated"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Kind      string             `json:"kind"`
}

type Device struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	NtfyTopic string             `json:"ntfy_topic"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DmGroup struct {
	ID        pgtype.UUID        `json:"id"`
	OwnerID   pgtype.UUID        `json:"owner_id"`
	Name      *string            `json:"name"`
	IconKey   *string            `json:"icon_key"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DmGroupInvite struct {
	Code      string             `json:"code"`
	GroupID   pgtype.UUID        `json:"group_id"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type DmGroupMember struct {
	GroupID  pgtype.UUID        `json:"group_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type DmGroupMessage struct {
	ID        pgtype.UUID        `json:"id"`
	GroupID   pgtype.UUID        `json:"group_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EmailChangeToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	NewEmail  string             `json:"new_email"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type EmailVerification struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	SpaceID     pgtype.UUID        `json:"space_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Location    *string            `json:"location"`
	StartsAt    pgtype.Timestamptz `json:"starts_at"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type EventRsvp struct {
	EventID     pgtype.UUID        `json:"event_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Status      string             `json:"status"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
}

type File struct {
	ID         pgtype.UUID        `json:"id"`
	OwnerID    pgtype.UUID        `json:"owner_id"`
	Filename   string             `json:"filename"`
	Size       int64              `json:"size"`
	Mimetype   string             `json:"mimetype"`
	Path       string             `json:"path"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	Sha256     string             `json:"sha256"`
	Kind       string             `json:"kind"`
	ScanStatus string             `json:"scan_status"`
}

type Friendship struct {
	ID          pgtype.UUID        `json:"id"`
	RequesterID pgtype.UUID        `json:"requester_id"`
	AddresseeID pgtype.UUID        `json:"addressee_id"`
	Status      string             `json:"status"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Game struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	CoverKey     *string            `json:"cover_key"`
	Status       string             `json:"status"`
	SubmittedBy  pgtype.UUID        `json:"submitted_by"`
	ReviewedBy   pgtype.UUID        `json:"reviewed_by"`
	RejectReason *string            `json:"reject_reason"`
	Aliases      []string           `json:"aliases"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type InboxItem struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Kind      string             `json:"kind"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	ArchiveID string             `json:"archive_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Preview   *string            `json:"preview"`
	Read      bool               `json:"read"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Invite struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	CreatorID pgtype.UUID        `json:"creator_id"`
	Code      string             `json:"code"`
	MaxUses   *int32             `json:"max_uses"`
	Uses      *int32             `json:"uses"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type JoinForm struct {
	SpaceID    pgtype.UUID        `json:"space_id"`
	Enabled    bool               `json:"enabled"`
	Questions  []byte             `json:"questions"`
	AutoRoleID pgtype.UUID        `json:"auto_role_id"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	MinKarma   int32              `json:"min_karma"`
}

type JoinRequest struct {
	ID         pgtype.UUID        `json:"id"`
	SpaceID    pgtype.UUID        `json:"space_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	Answers    []byte             `json:"answers"`
	Status     string             `json:"status"`
	ReviewedBy pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt pgtype.Timestamptz `json:"reviewed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Karma struct {
	UserID    pgtype.UUID        `json:"user_id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	Score     int32              `json:"score"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type KarmaEvent struct {
	ID         pgtype.UUID        `json:"id"`
	SpaceID    pgtype.UUID        `json:"space_id"`
	TargetUser pgtype.UUID        `json:"target_user"`
	SourceUser pgtype.UUID        `json:"source_user"`
	Delta      int32              `json:"delta"`
	Reason     string             `json:"reason"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type MaliciousUrl struct {
	UrlHash string             `json:"url_hash"`
	Threat  *string            `json:"threat"`
	AddedAt pgtype.Timestamptz `json:"added_at"`
}

type Member struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Nickname  *string            `json:"nickname"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	AvatarKey *string            `json:"avatar_key"`
	Bio       *string            `json:"bio"`
}

type MemberRole struct {
	MemberID  pgtype.UUID        `json:"member_id"`
	RoleID    pgtype.UUID        `json:"role_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type MessageFollow struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	ArchiveID string             `json:"archive_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type MessagePin struct {
	ID        pgtype.UUID        `json:"id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	ArchiveID string             `json:"archive_id"`
	PinnedBy  pgtype.UUID        `json:"pinned_by"`
	Note      string             `json:"note"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type ModAction struct {
	ID          pgtype.UUID        `json:"id"`
	SpaceID     pgtype.UUID        `json:"space_id"`
	TargetUser  pgtype.UUID        `json:"target_user"`
	ModeratorID pgtype.UUID        `json:"moderator_id"`
	Action      string             `json:"action"`
	Reason      *string            `json:"reason"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type NotifSetting struct {
	UserID           pgtype.UUID        `json:"user_id"`
	ScopeType        string             `json:"scope_type"`
	ScopeID          pgtype.UUID        `json:"scope_id"`
	Level            string             `json:"level"`
	MutedUntil       pgtype.Timestamptz `json:"muted_until"`
	SuppressEveryone bool               `json:"suppress_everyone"`
}

type OauthAccount struct {
	ID         pgtype.UUID `json:"id"`
	UserID     pgtype.UUID `json:"user_id"`
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
}

type Poll struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	Question  string             `json:"question"`
	CreatedBy pgtype.UUID        `json:"created_by"`
	Closed    bool               `json:"closed"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PollOption struct {
	ID       pgtype.UUID `json:"id"`
	PollID   pgtype.UUID `json:"poll_id"`
	Label    string      `json:"label"`
	Position int32       `json:"position"`
}

type PollVote struct {
	PollID   pgtype.UUID        `json:"poll_id"`
	OptionID pgtype.UUID        `json:"option_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	VotedAt  pgtype.Timestamptz `json:"voted_at"`
}

type PushPref struct {
	UserID  pgtype.UUID `json:"user_id"`
	SpaceID pgtype.UUID `json:"space_id"`
	Scope   string      `json:"scope"`
}

type Report struct {
	ID         pgtype.UUID        `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	TargetType string             `json:"target_type"`
	TargetID   pgtype.UUID        `json:"target_id"`
	Reason     string             `json:"reason"`
	Status     *string            `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	SpaceID    pgtype.UUID        `json:"space_id"`
	ChannelID  pgtype.UUID        `json:"channel_id"`
	ResolvedBy pgtype.UUID        `json:"resolved_by"`
	ResolvedAt pgtype.Timestamptz `json:"resolved_at"`
	Category   *string            `json:"category"`
	Context    []byte             `json:"context"`
	AssignedTo pgtype.UUID        `json:"assigned_to"`
}

type ReportComment struct {
	ID        pgtype.UUID        `json:"id"`
	ReportID  pgtype.UUID        `json:"report_id"`
	AuthorID  pgtype.UUID        `json:"author_id"`
	Body      string             `json:"body"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type RiverClient struct {
	ID        string             `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RiverClientQueue struct {
	RiverClientID    string             `json:"river_client_id"`
	Name             string             `json:"name"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	MaxWorkers       int64              `json:"max_workers"`
	Metadata         []byte             `json:"metadata"`
	NumJobsCompleted int64              `json:"num_jobs_completed"`
	NumJobsRunning   int64              `json:"num_jobs_running"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type RiverJob struct {
	ID           int64              `json:"id"`
	State        RiverJobState      `json:"state"`
	Attempt      int16              `json:"attempt"`
	MaxAttempts  int16              `json:"max_attempts"`
	AttemptedAt  pgtype.Timestamptz `json:"attempted_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FinalizedAt  pgtype.Timestamptz `json:"finalized_at"`
	ScheduledAt  pgtype.Timestamptz `json:"scheduled_at"`
	Priority     int16              `json:"priority"`
	Args         []byte             `json:"args"`
	AttemptedBy  []string           `json:"attempted_by"`
	Errors       [][]byte           `json:"errors"`
	Kind         string             `json:"kind"`
	Metadata     []byte             `json:"metadata"`
	Queue        string             `json:"queue"`
	Tags         []string           `json:"tags"`
	UniqueKey    []byte             `json:"unique_key"`
	UniqueStates pgtype.Bits        `json:"unique_states"`
}

type RiverLeader struct {
	ElectedAt pgtype.Timestamptz `json:"elected_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	LeaderID  string             `json:"leader_id"`
	Name      string             `json:"name"`
}

type RiverQueue struct {
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	Metadata  []byte             `json:"metadata"`
	PausedAt  pgtype.Timestamptz `json:"paused_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID          pgtype.UUID `json:"id"`
	SpaceID     pgtype.UUID `json:"space_id"`
	Name        string      `json:"name"`
	Permissions *int64      `json:"permissions"`
	Color       *string     `json:"color"`
	Position    *int32      `json:"position"`
	IsEveryone  *bool       `json:"is_everyone"`
	Hoist       bool        `json:"hoist"`
	Mentionable bool        `json:"mentionable"`
	IconEmoji   *string     `json:"icon_emoji"`
}

type SavedMessage struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	ArchiveID string             `json:"archive_id"`
	Folder    string             `json:"folder"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SavedSearch struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	Name      string             `json:"name"`
	Query     string             `json:"query"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	FamilyID     pgtype.UUID        `json:"family_id"`
	ReplacedBy   pgtype.UUID        `json:"replaced_by"`
	UsedAt       pgtype.Timestamptz `json:"used_at"`
}

type Space struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerID     pgtype.UUID        `json:"owner_id"`
	Name        string             `json:"name"`
	IconKey     *string            `json:"icon_key"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Description *string            `json:"description"`
	Rules       *string            `json:"rules"`
	BannerKey   *string            `json:"banner_key"`
	Tags        []string           `json:"tags"`
	Language    *string            `json:"language"`
	VanitySlug  *string            `json:"vanity_slug"`
}

type SpaceListing struct {
	SpaceID     pgtype.UUID        `json:"space_id"`
	Category    string             `json:"category"`
	MemberCount int32              `json:"member_count"`
	ListedAt    pgtype.Timestamptz `json:"listed_at"`
	DelistedAt  pgtype.Timestamptz `json:"delisted_at"`
}

type Task struct {
	ID              pgtype.UUID        `json:"id"`
	SpaceID         pgtype.UUID        `json:"space_id"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	SourceArchiveID *string            `json:"source_archive_id"`
	Title           string             `json:"title"`
	AssigneeID      pgtype.UUID        `json:"assignee_id"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
	Status          string             `json:"status"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Thread struct {
	ID             pgtype.UUID        `json:"id"`
	ChannelID      pgtype.UUID        `json:"channel_id"`
	RootArchiveID  string             `json:"root_archive_id"`
	Title          string             `json:"title"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	LastActivityAt pgtype.Timestamptz `json:"last_activity_at"`
}

type ThreadSubscription struct {
	UserID    pgtype.UUID        `json:"user_id"`
	ThreadID  pgtype.UUID        `json:"thread_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                   pgtype.UUID        `json:"id"`
	Username             string             `json:"username"`
	Email                string             `json:"email"`
	PasswordHash         *string            `json:"password_hash"`
	AvatarKey            *string            `json:"avatar_key"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	DisplayName          *string            `json:"display_name"`
	Status               *string            `json:"status"`
	IsAdmin              bool               `json:"is_admin"`
	Disabled             bool               `json:"disabled"`
	WhoCanAdd            string             `json:"who_can_add"`
	BannerKey            *string            `json:"banner_key"`
	Bio                  *string            `json:"bio"`
	Pronouns             *string            `json:"pronouns"`
	Links                []byte             `json:"links"`
	AccentColor          *string            `json:"accent_color"`
	SignupIpHash         *string            `json:"signup_ip_hash"`
	Badges               []string           `json:"badges"`
	Tier                 string             `json:"tier"`
	StripeCustomerID     *string            `json:"stripe_customer_id"`
	StripeSubscriptionID *string            `json:"stripe_subscription_id"`
	SubscriptionStatus   *string            `json:"subscription_status"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	TotpSecret           *string            `json:"totp_secret"`
	TotpEnabled          bool               `json:"totp_enabled"`
	BackupCodes          []byte             `json:"backup_codes"`
	EmailVerified        bool               `json:"email_verified"`
}

type Webhook struct {
	ID        pgtype.UUID        `json:"id"`
	SpaceID   pgtype.UUID        `json:"space_id"`
	ChannelID pgtype.UUID        `json:"channel_id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	Secret    *string            `json:"secret"`
	Events    []string           `json:"events"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type XmppToken struct {
	Token     string             `json:"token"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
