// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInboxUnread = `-- name: CountInboxUnread :one
SELECT COUNT(*) FROM inbox_items WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) CountInboxUnread(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countInboxUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createInboxItem = `-- name: CreateInboxItem :exec
INSERT INTO inbox_items (user_id, kind, space_id, channel_id, archive_id, author_id, preview)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, channel_id, archive_id) DO NOTHING
`

type CreateInboxItemParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Kind      string      `json:"kind"`
	SpaceID   pgtype.UUID `json:"space_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
	AuthorID  pgtype.UUID `json:"author_id"`
	Preview   *string     `json:"preview"`
}

func (q *Queries) CreateInboxItem(ctx context.Context, arg CreateInboxItemParams) error {
	_, err := q.db.Exec(ctx, createInboxItem,
		arg.UserID,
		arg.Kind,
		arg.SpaceID,
		arg.ChannelID,
		arg.ArchiveID,
		arg.AuthorID,
		arg.Preview,
	)
	return err
}

const deleteNotifSetting = `-- name: DeleteNotifSetting :exec
DELETE FROM notif_settings
 WHERE user_id = $1 AND scope_type = $2 AND scope_id = $3
`

type DeleteNotifSettingParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
}

func (q *Queries) DeleteNotifSetting(ctx context.Context, arg DeleteNotifSettingParams) error {
	_, err := q.db.Exec(ctx, deleteNotifSetting, arg.UserID, arg.ScopeType, arg.ScopeID)
	return err
}

const getNotifSetting = `-- name: GetNotifSetting :one
SELECT user_id, scope_type, scope_id, level, muted_until, suppress_everyone FROM notif_settings
 WHERE user_id = $1 AND scope_type = $2 AND scope_id = $3
`

type GetNotifSettingParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ScopeType string      `json:"scope_type"`
	ScopeID   pgtype.UUID `json:"scope_id"`
}

func (q *Queries) GetNotifSetting(ctx context.Context, arg GetNotifSettingParams) (NotifSetting, error) {
	row := q.db.QueryRow(ctx, getNotifSetting, arg.UserID, arg.ScopeType, arg.ScopeID)
	var i NotifSetting
	err := row.Scan(
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Level,
		&i.MutedUntil,
		&i.SuppressEveryone,
	)
	return i, err
}

const listInbox = `-- name: ListInbox :many
SELECT id, user_id, kind, space_id, channel_id, archive_id, author_id, preview, read, created_at FROM inbox_items
 WHERE user_id = $1
 ORDER BY created_at DESC
 LIMIT $2
`

type ListInboxParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListInbox(ctx context.Context, arg ListInboxParams) ([]InboxItem, error) {
	rows, err := q.db.Query(ctx, listInbox, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InboxItem{}
	for rows.Next() {
		var i InboxItem
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Kind,
			&i.SpaceID,
			&i.ChannelID,
			&i.ArchiveID,
			&i.AuthorID,
			&i.Preview,
			&i.Read,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifSettings = `-- name: ListNotifSettings :many
SELECT user_id, scope_type, scope_id, level, muted_until, suppress_everyone FROM notif_settings WHERE user_id = $1
`

func (q *Queries) ListNotifSettings(ctx context.Context, userID pgtype.UUID) ([]NotifSetting, error) {
	rows, err := q.db.Query(ctx, listNotifSettings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotifSetting{}
	for rows.Next() {
		var i NotifSetting
		if err := rows.Scan(
			&i.UserID,
			&i.ScopeType,
			&i.ScopeID,
			&i.Level,
			&i.MutedUntil,
			&i.SuppressEveryone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllInboxRead = `-- name: MarkAllInboxRead :exec
UPDATE inbox_items SET read = TRUE WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) MarkAllInboxRead(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllInboxRead, userID)
	return err
}

const markInboxItemRead = `-- name: MarkInboxItemRead :exec
UPDATE inbox_items SET read = TRUE WHERE id = $1 AND user_id = $2
`

type MarkInboxItemReadParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) MarkInboxItemRead(ctx context.Context, arg MarkInboxItemReadParams) error {
	_, err := q.db.Exec(ctx, markInboxItemRead, arg.ID, arg.UserID)
	return err
}

const upsertNotifSetting = `-- name: UpsertNotifSetting :one
INSERT INTO notif_settings (user_id, scope_type, scope_id, level, muted_until, suppress_everyone)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, scope_type, scope_id)
DO UPDATE SET level = EXCLUDED.level,
              muted_until = EXCLUDED.muted_until,
              suppress_everyone = EXCLUDED.suppress_everyone
RETURNING user_id, scope_type, scope_id, level, muted_until, suppress_everyone
`

type UpsertNotifSettingParams struct {
	UserID           pgtype.UUID        `json:"user_id"`
	ScopeType        string             `json:"scope_type"`
	ScopeID          pgtype.UUID        `json:"scope_id"`
	Level            string             `json:"level"`
	MutedUntil       pgtype.Timestamptz `json:"muted_until"`
	SuppressEveryone bool               `json:"suppress_everyone"`
}

func (q *Queries) UpsertNotifSetting(ctx context.Context, arg UpsertNotifSettingParams) (NotifSetting, error) {
	row := q.db.QueryRow(ctx, upsertNotifSetting,
		arg.UserID,
		arg.ScopeType,
		arg.ScopeID,
		arg.Level,
		arg.MutedUntil,
		arg.SuppressEveryone,
	)
	var i NotifSetting
	err := row.Scan(
		&i.UserID,
		&i.ScopeType,
		&i.ScopeID,
		&i.Level,
		&i.MutedUntil,
		&i.SuppressEveryone,
	)
	return i, err
}
