// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: overwrites.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteMemberOverwrite = `-- name: DeleteMemberOverwrite :exec
DELETE FROM channel_overwrites WHERE channel_id = $1 AND member_id = $2
`

type DeleteMemberOverwriteParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	MemberID  pgtype.UUID `json:"member_id"`
}

func (q *Queries) DeleteMemberOverwrite(ctx context.Context, arg DeleteMemberOverwriteParams) error {
	_, err := q.db.Exec(ctx, deleteMemberOverwrite, arg.ChannelID, arg.MemberID)
	return err
}

const deleteRoleOverwrite = `-- name: DeleteRoleOverwrite :exec
DELETE FROM channel_overwrites WHERE channel_id = $1 AND role_id = $2
`

type DeleteRoleOverwriteParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	RoleID    pgtype.UUID `json:"role_id"`
}

func (q *Queries) DeleteRoleOverwrite(ctx context.Context, arg DeleteRoleOverwriteParams) error {
	_, err := q.db.Exec(ctx, deleteRoleOverwrite, arg.ChannelID, arg.RoleID)
	return err
}

const getMemberChannelOverwrite = `-- name: GetMemberChannelOverwrite :one

SELECT channel_id, role_id, allow, deny, member_id FROM channel_overwrites
 WHERE channel_id = $1 AND member_id = $2
`

type GetMemberChannelOverwriteParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	MemberID  pgtype.UUID `json:"member_id"`
}

func (q *Queries) GetMemberChannelOverwrite(ctx context.Context, arg GetMemberChannelOverwriteParams) (ChannelOverwrite, error) {
	row := q.db.QueryRow(ctx, getMemberChannelOverwrite, arg.ChannelID, arg.MemberID)
	var i ChannelOverwrite
	err := row.Scan(
		&i.ChannelID,
		&i.RoleID,
		&i.Allow,
		&i.Deny,
		&i.MemberID,
	)
	return i, err
}

const listChannelOverwrites = `-- name: ListChannelOverwrites :many

SELECT channel_id, role_id, allow, deny, member_id FROM channel_overwrites
 WHERE channel_id = $1
`

func (q *Queries) ListChannelOverwrites(ctx context.Context, channelID pgtype.UUID) ([]ChannelOverwrite, error) {
	rows, err := q.db.Query(ctx, listChannelOverwrites, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelOverwrite{}
	for rows.Next() {
		var i ChannelOverwrite
		if err := rows.Scan(
			&i.ChannelID,
			&i.RoleID,
			&i.Allow,
			&i.Deny,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMemberOverwrite = `-- name: UpsertMemberOverwrite :one
INSERT INTO channel_overwrites (channel_id, member_id, allow, deny)
VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, member_id) WHERE member_id IS NOT NULL
DO UPDATE SET allow = EXCLUDED.allow, deny = EXCLUDED.deny
RETURNING channel_id, role_id, allow, deny, member_id
`

type UpsertMemberOverwriteParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	MemberID  pgtype.UUID `json:"member_id"`
	Allow     *int64      `json:"allow"`
	Deny      *int64      `json:"deny"`
}

func (q *Queries) UpsertMemberOverwrite(ctx context.Context, arg UpsertMemberOverwriteParams) (ChannelOverwrite, error) {
	row := q.db.QueryRow(ctx, upsertMemberOverwrite,
		arg.ChannelID,
		arg.MemberID,
		arg.Allow,
		arg.Deny,
	)
	var i ChannelOverwrite
	err := row.Scan(
		&i.ChannelID,
		&i.RoleID,
		&i.Allow,
		&i.Deny,
		&i.MemberID,
	)
	return i, err
}

const upsertRoleOverwrite = `-- name: UpsertRoleOverwrite :one
INSERT INTO channel_overwrites (channel_id, role_id, allow, deny)
VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, role_id) WHERE role_id IS NOT NULL
DO UPDATE SET allow = EXCLUDED.allow, deny = EXCLUDED.deny
RETURNING channel_id, role_id, allow, deny, member_id
`

type UpsertRoleOverwriteParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	RoleID    pgtype.UUID `json:"role_id"`
	Allow     *int64      `json:"allow"`
	Deny      *int64      `json:"deny"`
}

func (q *Queries) UpsertRoleOverwrite(ctx context.Context, arg UpsertRoleOverwriteParams) (ChannelOverwrite, error) {
	row := q.db.QueryRow(ctx, upsertRoleOverwrite,
		arg.ChannelID,
		arg.RoleID,
		arg.Allow,
		arg.Deny,
	)
	var i ChannelOverwrite
	err := row.Scan(
		&i.ChannelID,
		&i.RoleID,
		&i.Allow,
		&i.Deny,
		&i.MemberID,
	)
	return i, err
}
