// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pins.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPin = `-- name: CreatePin :one
INSERT INTO message_pins (channel_id, archive_id, pinned_by, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (channel_id, archive_id)
    DO UPDATE SET note = EXCLUDED.note
RETURNING id, channel_id, archive_id, pinned_by, note, created_at
`

type CreatePinParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
	PinnedBy  pgtype.UUID `json:"pinned_by"`
	Note      string      `json:"note"`
}

func (q *Queries) CreatePin(ctx context.Context, arg CreatePinParams) (MessagePin, error) {
	row := q.db.QueryRow(ctx, createPin,
		arg.ChannelID,
		arg.ArchiveID,
		arg.PinnedBy,
		arg.Note,
	)
	var i MessagePin
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.ArchiveID,
		&i.PinnedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const deletePin = `-- name: DeletePin :execrows
DELETE FROM message_pins
 WHERE channel_id = $1 AND archive_id = $2
`

type DeletePinParams struct {
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
}

func (q *Queries) DeletePin(ctx context.Context, arg DeletePinParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePin, arg.ChannelID, arg.ArchiveID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listChannelPins = `-- name: ListChannelPins :many
SELECT id, channel_id, archive_id, pinned_by, note, created_at FROM message_pins
 WHERE channel_id = $1
 ORDER BY created_at DESC
`

func (q *Queries) ListChannelPins(ctx context.Context, channelID pgtype.UUID) ([]MessagePin, error) {
	rows, err := q.db.Query(ctx, listChannelPins, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessagePin{}
	for rows.Next() {
		var i MessagePin
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.ArchiveID,
			&i.PinnedBy,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
