// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: polls.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const castVote = `-- name: CastVote :exec
INSERT INTO poll_votes (poll_id, option_id, user_id)
VALUES ($1, $2, $3)
ON CONFLICT (poll_id, user_id)
DO UPDATE SET option_id = EXCLUDED.option_id, voted_at = NOW()
`

type CastVoteParams struct {
	PollID   pgtype.UUID `json:"poll_id"`
	OptionID pgtype.UUID `json:"option_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) CastVote(ctx context.Context, arg CastVoteParams) error {
	_, err := q.db.Exec(ctx, castVote, arg.PollID, arg.OptionID, arg.UserID)
	return err
}

const closePoll = `-- name: ClosePoll :one
UPDATE polls SET closed = TRUE WHERE id = $1 RETURNING id, space_id, channel_id, question, created_by, closed, created_at
`

func (q *Queries) ClosePoll(ctx context.Context, id pgtype.UUID) (Poll, error) {
	row := q.db.QueryRow(ctx, closePoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Question,
		&i.CreatedBy,
		&i.Closed,
		&i.CreatedAt,
	)
	return i, err
}

const createPoll = `-- name: CreatePoll :one
INSERT INTO polls (space_id, channel_id, question, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, space_id, channel_id, question, created_by, closed, created_at
`

type CreatePollParams struct {
	SpaceID   pgtype.UUID `json:"space_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	Question  string      `json:"question"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error) {
	row := q.db.QueryRow(ctx, createPoll,
		arg.SpaceID,
		arg.ChannelID,
		arg.Question,
		arg.CreatedBy,
	)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Question,
		&i.CreatedBy,
		&i.Closed,
		&i.CreatedAt,
	)
	return i, err
}

const createPollOption = `-- name: CreatePollOption :one
INSERT INTO poll_options (poll_id, label, position)
VALUES ($1, $2, $3)
RETURNING id, poll_id, label, position
`

type CreatePollOptionParams struct {
	PollID   pgtype.UUID `json:"poll_id"`
	Label    string      `json:"label"`
	Position int32       `json:"position"`
}

func (q *Queries) CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PollOption, error) {
	row := q.db.QueryRow(ctx, createPollOption, arg.PollID, arg.Label, arg.Position)
	var i PollOption
	err := row.Scan(
		&i.ID,
		&i.PollID,
		&i.Label,
		&i.Position,
	)
	return i, err
}

const getMyVote = `-- name: GetMyVote :one
SELECT option_id FROM poll_votes WHERE poll_id = $1 AND user_id = $2
`

type GetMyVoteParams struct {
	PollID pgtype.UUID `json:"poll_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMyVote(ctx context.Context, arg GetMyVoteParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getMyVote, arg.PollID, arg.UserID)
	var option_id pgtype.UUID
	err := row.Scan(&option_id)
	return option_id, err
}

const getPoll = `-- name: GetPoll :one
SELECT id, space_id, channel_id, question, created_by, closed, created_at FROM polls WHERE id = $1
`

func (q *Queries) GetPoll(ctx context.Context, id pgtype.UUID) (Poll, error) {
	row := q.db.QueryRow(ctx, getPoll, id)
	var i Poll
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Question,
		&i.CreatedBy,
		&i.Closed,
		&i.CreatedAt,
	)
	return i, err
}

const listChannelPolls = `-- name: ListChannelPolls :many
SELECT id, space_id, channel_id, question, created_by, closed, created_at FROM polls WHERE channel_id = $1 ORDER BY created_at DESC LIMIT 100
`

func (q *Queries) ListChannelPolls(ctx context.Context, channelID pgtype.UUID) ([]Poll, error) {
	rows, err := q.db.Query(ctx, listChannelPolls, channelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Poll{}
	for rows.Next() {
		var i Poll
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.Question,
			&i.CreatedBy,
			&i.Closed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPollOptions = `-- name: ListPollOptions :many
SELECT id, poll_id, label, position FROM poll_options WHERE poll_id = $1 ORDER BY position, id
`

func (q *Queries) ListPollOptions(ctx context.Context, pollID pgtype.UUID) ([]PollOption, error) {
	rows, err := q.db.Query(ctx, listPollOptions, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PollOption{}
	for rows.Next() {
		var i PollOption
		if err := rows.Scan(
			&i.ID,
			&i.PollID,
			&i.Label,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optionInPoll = `-- name: OptionInPoll :one
SELECT EXISTS (SELECT 1 FROM poll_options WHERE id = $1 AND poll_id = $2) AS ok
`

type OptionInPollParams struct {
	ID     pgtype.UUID `json:"id"`
	PollID pgtype.UUID `json:"poll_id"`
}

func (q *Queries) OptionInPoll(ctx context.Context, arg OptionInPollParams) (bool, error) {
	row := q.db.QueryRow(ctx, optionInPoll, arg.ID, arg.PollID)
	var ok bool
	err := row.Scan(&ok)
	return ok, err
}

const pollResults = `-- name: PollResults :many
SELECT o.id AS option_id, COUNT(v.user_id) AS votes
  FROM poll_options o
  LEFT JOIN poll_votes v ON v.option_id = o.id
 WHERE o.poll_id = $1
 GROUP BY o.id
`

type PollResultsRow struct {
	OptionID pgtype.UUID `json:"option_id"`
	Votes    int64       `json:"votes"`
}

func (q *Queries) PollResults(ctx context.Context, pollID pgtype.UUID) ([]PollResultsRow, error) {
	rows, err := q.db.Query(ctx, pollResults, pollID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PollResultsRow{}
	for rows.Next() {
		var i PollResultsRow
		if err := rows.Scan(&i.OptionID, &i.Votes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
