// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, ntfy_topic)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, ntfy_topic) DO UPDATE SET name = EXCLUDED.name
RETURNING id, user_id, name, ntfy_topic, created_at
`

type CreateDeviceParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	Name      string      `json:"name"`
	NtfyTopic string      `json:"ntfy_topic"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice, arg.UserID, arg.Name, arg.NtfyTopic)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.NtfyTopic,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.Exec(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getPushPref = `-- name: GetPushPref :one
SELECT user_id, space_id, scope FROM push_prefs WHERE user_id = $1 AND space_id = $2
`

type GetPushPrefParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	SpaceID pgtype.UUID `json:"space_id"`
}

func (q *Queries) GetPushPref(ctx context.Context, arg GetPushPrefParams) (PushPref, error) {
	row := q.db.QueryRow(ctx, getPushPref, arg.UserID, arg.SpaceID)
	var i PushPref
	err := row.Scan(&i.UserID, &i.SpaceID, &i.Scope)
	return i, err
}

const listUserDevices = `-- name: ListUserDevices :many
SELECT id, user_id, name, ntfy_topic, created_at FROM devices WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserDevices(ctx context.Context, userID pgtype.UUID) ([]Device, error) {
	rows, err := q.db.Query(ctx, listUserDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Device{}
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.NtfyTopic,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPushPrefs = `-- name: ListUserPushPrefs :many
SELECT user_id, space_id, scope FROM push_prefs WHERE user_id = $1
`

func (q *Queries) ListUserPushPrefs(ctx context.Context, userID pgtype.UUID) ([]PushPref, error) {
	rows, err := q.db.Query(ctx, listUserPushPrefs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PushPref{}
	for rows.Next() {
		var i PushPref
		if err := rows.Scan(&i.UserID, &i.SpaceID, &i.Scope); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPushPref = `-- name: UpsertPushPref :one
INSERT INTO push_prefs (user_id, space_id, scope)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, space_id) DO UPDATE SET scope = EXCLUDED.scope
RETURNING user_id, space_id, scope
`

type UpsertPushPrefParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	SpaceID pgtype.UUID `json:"space_id"`
	Scope   string      `json:"scope"`
}

func (q *Queries) UpsertPushPref(ctx context.Context, arg UpsertPushPrefParams) (PushPref, error) {
	row := q.db.QueryRow(ctx, upsertPushPref, arg.UserID, arg.SpaceID, arg.Scope)
	var i PushPref
	err := row.Scan(&i.UserID, &i.SpaceID, &i.Scope)
	return i, err
}
