// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptFriendRequest(ctx context.Context, arg AcceptFriendRequestParams) (Friendship, error)
	AddDMGroupMember(ctx context.Context, arg AddDMGroupMemberParams) error
	AddKarma(ctx context.Context, arg AddKarmaParams) (int32, error)
	AssignMemberRole(ctx context.Context, arg AssignMemberRoleParams) error
	CastVote(ctx context.Context, arg CastVoteParams) error
	ClaimReport(ctx context.Context, arg ClaimReportParams) (Report, error)
	ClosePoll(ctx context.Context, id pgtype.UUID) (Poll, error)
	ConsumeEmailChangeToken(ctx context.Context, tokenHash string) (EmailChangeToken, error)
	ConsumeSession(ctx context.Context, arg ConsumeSessionParams) (Session, error)
	ConsumeXMPPToken(ctx context.Context, token string) (XmppToken, error)
	CountAccountsBySignupIPHash(ctx context.Context, signupIpHash *string) (int64, error)
	CountDMGroupMembers(ctx context.Context, groupID pgtype.UUID) (int64, error)
	CountInboxUnread(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountKarmaEventsBySourceSince(ctx context.Context, arg CountKarmaEventsBySourceSinceParams) (int64, error)
	CountPendingReports(ctx context.Context, spaceID pgtype.UUID) (int64, error)
	CountSavedSearches(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountSpaceEmojis(ctx context.Context, arg CountSpaceEmojisParams) (int64, error)
	CountSpaceMembers(ctx context.Context, spaceID pgtype.UUID) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error)
	CreateBan(ctx context.Context, arg CreateBanParams) (Ban, error)
	CreateBannedIdentifier(ctx context.Context, arg CreateBannedIdentifierParams) error
	CreateBlock(ctx context.Context, arg CreateBlockParams) error
	CreateBot(ctx context.Context, arg CreateBotParams) (Bot, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error)
	CreateCustomEmoji(ctx context.Context, arg CreateCustomEmojiParams) (CustomEmoji, error)
	CreateDMGroup(ctx context.Context, arg CreateDMGroupParams) (DmGroup, error)
	CreateDMGroupInvite(ctx context.Context, arg CreateDMGroupInviteParams) error
	CreateDMGroupMessage(ctx context.Context, arg CreateDMGroupMessageParams) (DmGroupMessage, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateEmailChangeToken(ctx context.Context, arg CreateEmailChangeTokenParams) (EmailChangeToken, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateFriendRequest(ctx context.Context, arg CreateFriendRequestParams) (Friendship, error)
	CreateInboxItem(ctx context.Context, arg CreateInboxItemParams) error
	CreateInvite(ctx context.Context, arg CreateInviteParams) (Invite, error)
	CreateJoinRequest(ctx context.Context, arg CreateJoinRequestParams) (JoinRequest, error)
	CreateMember(ctx context.Context, arg CreateMemberParams) (Member, error)
	CreateModAction(ctx context.Context, arg CreateModActionParams) (ModAction, error)
	CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error)
	CreatePin(ctx context.Context, arg CreatePinParams) (MessagePin, error)
	CreatePoll(ctx context.Context, arg CreatePollParams) (Poll, error)
	CreatePollOption(ctx context.Context, arg CreatePollOptionParams) (PollOption, error)
	CreateReport(ctx context.Context, arg CreateReportParams) (Report, error)
	CreateReportComment(ctx context.Context, arg CreateReportCommentParams) (ReportComment, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateSavedMessage(ctx context.Context, arg CreateSavedMessageParams) (SavedMessage, error)
	CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateSessionInFamily(ctx context.Context, arg CreateSessionInFamilyParams) (Session, error)
	CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CreateXMPPToken(ctx context.Context, arg CreateXMPPTokenParams) (XmppToken, error)
	DeactivateExpiredTimeouts(ctx context.Context) error
	DeleteAPIToken(ctx context.Context, arg DeleteAPITokenParams) error
	DeleteBan(ctx context.Context, arg DeleteBanParams) error
	DeleteBlock(ctx context.Context, arg DeleteBlockParams) error
	DeleteBot(ctx context.Context, id pgtype.UUID) error
	DeleteCategory(ctx context.Context, id pgtype.UUID) error
	DeleteChannel(ctx context.Context, id pgtype.UUID) error
	DeleteCustomEmoji(ctx context.Context, id pgtype.UUID) error
	DeleteDMGroup(ctx context.Context, id pgtype.UUID) error
	DeleteDMGroupInvite(ctx context.Context, arg DeleteDMGroupInviteParams) error
	DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error
	DeleteEmailVerification(ctx context.Context, userID pgtype.UUID) error
	DeleteEvent(ctx context.Context, id pgtype.UUID) error
	DeleteExpiredInvites(ctx context.Context) error
	DeleteExpiredMemberRoles(ctx context.Context) (int64, error)
	DeleteExpiredSessions(ctx context.Context) error
	DeleteExpiredXMPPTokens(ctx context.Context) error
	DeleteFile(ctx context.Context, id pgtype.UUID) error
	DeleteFriendship(ctx context.Context, arg DeleteFriendshipParams) error
	DeleteFriendshipByPair(ctx context.Context, arg DeleteFriendshipByPairParams) error
	DeleteInvite(ctx context.Context, id pgtype.UUID) error
	DeleteInviteByCode(ctx context.Context, code string) error
	DeleteMember(ctx context.Context, id pgtype.UUID) error
	DeleteMemberOverwrite(ctx context.Context, arg DeleteMemberOverwriteParams) error
	DeleteNotifSetting(ctx context.Context, arg DeleteNotifSettingParams) error
	DeletePin(ctx context.Context, arg DeletePinParams) (int64, error)
	DeleteRole(ctx context.Context, id pgtype.UUID) error
	DeleteRoleOverwrite(ctx context.Context, arg DeleteRoleOverwriteParams) error
	DeleteSavedMessage(ctx context.Context, arg DeleteSavedMessageParams) (int64, error)
	DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) (int64, error)
	DeleteSession(ctx context.Context, id pgtype.UUID) error
	DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error
	DeleteSessionFamily(ctx context.Context, familyID pgtype.UUID) error
	DeleteSpace(ctx context.Context, id pgtype.UUID) error
	DeleteTask(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error
	DeleteWebhook(ctx context.Context, id pgtype.UUID) error
	DelistSpace(ctx context.Context, spaceID pgtype.UUID) error
	DisableTOTP(ctx context.Context, id pgtype.UUID) error
	ExploreListings(ctx context.Context, arg ExploreListingsParams) ([]ExploreListingsRow, error)
	FindReusableInvite(ctx context.Context, arg FindReusableInviteParams) (Invite, error)
	FollowMessage(ctx context.Context, arg FollowMessageParams) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetActiveTimeout(ctx context.Context, arg GetActiveTimeoutParams) (ModAction, error)
	GetBan(ctx context.Context, arg GetBanParams) (Ban, error)
	GetBot(ctx context.Context, id pgtype.UUID) (Bot, error)
	GetCategory(ctx context.Context, id pgtype.UUID) (Category, error)
	GetChannel(ctx context.Context, id pgtype.UUID) (Channel, error)
	GetCustomEmoji(ctx context.Context, id pgtype.UUID) (CustomEmoji, error)
	GetDMGroup(ctx context.Context, id pgtype.UUID) (DmGroup, error)
	GetDMGroupInvite(ctx context.Context, code string) (DmGroupInvite, error)
	GetEmailVerification(ctx context.Context, userID pgtype.UUID) (GetEmailVerificationRow, error)
	GetEvent(ctx context.Context, id pgtype.UUID) (Event, error)
	GetEveryoneRole(ctx context.Context, spaceID pgtype.UUID) (Role, error)
	GetFile(ctx context.Context, id pgtype.UUID) (File, error)
	GetFileByOwnerSHA(ctx context.Context, arg GetFileByOwnerSHAParams) (File, error)
	GetFriendshipByID(ctx context.Context, id pgtype.UUID) (Friendship, error)
	GetFriendshipByPair(ctx context.Context, arg GetFriendshipByPairParams) (Friendship, error)
	GetGame(ctx context.Context, id pgtype.UUID) (Game, error)
	GetInviteByCode(ctx context.Context, code string) (Invite, error)
	GetJoinForm(ctx context.Context, spaceID pgtype.UUID) (JoinForm, error)
	GetJoinRequest(ctx context.Context, id pgtype.UUID) (JoinRequest, error)
	GetKarma(ctx context.Context, arg GetKarmaParams) (int32, error)
	GetListing(ctx context.Context, spaceID pgtype.UUID) (SpaceListing, error)
	GetMember(ctx context.Context, id pgtype.UUID) (Member, error)
	GetMemberByUser(ctx context.Context, arg GetMemberByUserParams) (Member, error)
	GetMemberChannelOverwrite(ctx context.Context, arg GetMemberChannelOverwriteParams) (ChannelOverwrite, error)
	GetMemberMaxRolePosition(ctx context.Context, memberID pgtype.UUID) (int32, error)
	GetMyRsvp(ctx context.Context, arg GetMyRsvpParams) (string, error)
	GetMyVote(ctx context.Context, arg GetMyVoteParams) (pgtype.UUID, error)
	GetNotifSetting(ctx context.Context, arg GetNotifSettingParams) (NotifSetting, error)
	GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error)
	GetPoll(ctx context.Context, id pgtype.UUID) (Poll, error)
	GetPushPref(ctx context.Context, arg GetPushPrefParams) (PushPref, error)
	GetReport(ctx context.Context, id pgtype.UUID) (Report, error)
	GetRole(ctx context.Context, id pgtype.UUID) (Role, error)
	GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetSpace(ctx context.Context, id pgtype.UUID) (Space, error)
	GetSpaceByVanity(ctx context.Context, lower string) (Space, error)
	GetTask(ctx context.Context, id pgtype.UUID) (Task, error)
	GetThread(ctx context.Context, id pgtype.UUID) (Thread, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByStripeCustomer(ctx context.Context, stripeCustomerID *string) (User, error)
	GetUserByUsername(ctx context.Context, lower string) (User, error)
	GetWebhook(ctx context.Context, id pgtype.UUID) (Webhook, error)
	HasMemberRole(ctx context.Context, arg HasMemberRoleParams) (bool, error)
	HasMutualFriend(ctx context.Context, arg HasMutualFriendParams) (bool, error)
	IncrementInviteUses(ctx context.Context, id pgtype.UUID) (Invite, error)
	InsertKarmaEvent(ctx context.Context, arg InsertKarmaEventParams) (pgtype.UUID, error)
	InvalidatePendingEmailChanges(ctx context.Context, userID pgtype.UUID) error
	IsBlockedEitherWay(ctx context.Context, arg IsBlockedEitherWayParams) (bool, error)
	IsDMGroupMember(ctx context.Context, arg IsDMGroupMemberParams) (bool, error)
	IsFollowingMessage(ctx context.Context, arg IsFollowingMessageParams) (bool, error)
	IsIdentifierBanned(ctx context.Context, arg IsIdentifierBannedParams) (bool, error)
	IsUserBanned(ctx context.Context, arg IsUserBannedParams) (bool, error)
	ListAcceptedFriends(ctx context.Context, requesterID pgtype.UUID) ([]ListAcceptedFriendsRow, error)
	ListApprovedGames(ctx context.Context, arg ListApprovedGamesParams) ([]Game, error)
	ListBlocks(ctx context.Context, blockerID pgtype.UUID) ([]ListBlocksRow, error)
	ListChannelOverwrites(ctx context.Context, channelID pgtype.UUID) ([]ChannelOverwrite, error)
	ListChannelOverwritesForRoles(ctx context.Context, arg ListChannelOverwritesForRolesParams) ([]ChannelOverwrite, error)
	ListChannelPins(ctx context.Context, channelID pgtype.UUID) ([]MessagePin, error)
	ListChannelPolls(ctx context.Context, channelID pgtype.UUID) ([]Poll, error)
	ListChannelThreads(ctx context.Context, arg ListChannelThreadsParams) ([]ListChannelThreadsRow, error)
	ListDMGroupInvites(ctx context.Context, groupID pgtype.UUID) ([]ListDMGroupInvitesRow, error)
	ListDMGroupMembers(ctx context.Context, groupID pgtype.UUID) ([]ListDMGroupMembersRow, error)
	ListDMGroupMessages(ctx context.Context, arg ListDMGroupMessagesParams) ([]ListDMGroupMessagesRow, error)
	ListGamesByStatus(ctx context.Context, arg ListGamesByStatusParams) ([]Game, error)
	ListInbox(ctx context.Context, arg ListInboxParams) ([]InboxItem, error)
	ListIncomingRequests(ctx context.Context, addresseeID pgtype.UUID) ([]ListIncomingRequestsRow, error)
	ListJoinRequests(ctx context.Context, arg ListJoinRequestsParams) ([]ListJoinRequestsRow, error)
	ListMemberRoles(ctx context.Context, memberID pgtype.UUID) ([]Role, error)
	ListMentionableRoleMembers(ctx context.Context, spaceID pgtype.UUID) ([]ListMentionableRoleMembersRow, error)
	ListMessageFollowers(ctx context.Context, arg ListMessageFollowersParams) ([]pgtype.UUID, error)
	ListMutualDMGroups(ctx context.Context, arg ListMutualDMGroupsParams) ([]ListMutualDMGroupsRow, error)
	ListMutualFriends(ctx context.Context, arg ListMutualFriendsParams) ([]ListMutualFriendsRow, error)
	ListMutualSpaces(ctx context.Context, arg ListMutualSpacesParams) ([]ListMutualSpacesRow, error)
	ListMyDMGroups(ctx context.Context, userID pgtype.UUID) ([]ListMyDMGroupsRow, error)
	ListNotifSettings(ctx context.Context, userID pgtype.UUID) ([]NotifSetting, error)
	ListOutgoingRequests(ctx context.Context, requesterID pgtype.UUID) ([]ListOutgoingRequestsRow, error)
	ListOwnerFiles(ctx context.Context, ownerID pgtype.UUID) ([]ListOwnerFilesRow, error)
	ListOwnerFilesByKind(ctx context.Context, arg ListOwnerFilesByKindParams) ([]File, error)
	ListPollOptions(ctx context.Context, pollID pgtype.UUID) ([]PollOption, error)
	ListReadState(ctx context.Context, userID pgtype.UUID) ([]ChannelReadState, error)
	ListReportComments(ctx context.Context, reportID pgtype.UUID) ([]ReportComment, error)
	ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error)
	ListRoleMembers(ctx context.Context, roleID pgtype.UUID) ([]ListRoleMembersRow, error)
	ListSavedMessages(ctx context.Context, userID pgtype.UUID) ([]SavedMessage, error)
	ListSavedSearches(ctx context.Context, userID pgtype.UUID) ([]SavedSearch, error)
	ListSpaceAuditLogs(ctx context.Context, arg ListSpaceAuditLogsParams) ([]AuditLog, error)
	ListSpaceBans(ctx context.Context, spaceID pgtype.UUID) ([]Ban, error)
	ListSpaceBots(ctx context.Context, spaceID pgtype.UUID) ([]Bot, error)
	ListSpaceCategories(ctx context.Context, spaceID pgtype.UUID) ([]Category, error)
	ListSpaceChannels(ctx context.Context, spaceID pgtype.UUID) ([]Channel, error)
	ListSpaceEmojis(ctx context.Context, arg ListSpaceEmojisParams) ([]CustomEmoji, error)
	ListSpaceEvents(ctx context.Context, spaceID pgtype.UUID) ([]Event, error)
	ListSpaceInvites(ctx context.Context, spaceID pgtype.UUID) ([]Invite, error)
	ListSpaceKarma(ctx context.Context, arg ListSpaceKarmaParams) ([]ListSpaceKarmaRow, error)
	ListSpaceMemberIDs(ctx context.Context, spaceID pgtype.UUID) ([]pgtype.UUID, error)
	ListSpaceMembers(ctx context.Context, spaceID pgtype.UUID) ([]ListSpaceMembersRow, error)
	ListSpaceModActions(ctx context.Context, arg ListSpaceModActionsParams) ([]ModAction, error)
	ListSpaceReports(ctx context.Context, arg ListSpaceReportsParams) ([]Report, error)
	ListSpaceRoles(ctx context.Context, spaceID pgtype.UUID) ([]Role, error)
	ListSpaceTasks(ctx context.Context, arg ListSpaceTasksParams) ([]Task, error)
	ListSpaceWebhooks(ctx context.Context, spaceID pgtype.UUID) ([]Webhook, error)
	ListUserAPITokens(ctx context.Context, userID pgtype.UUID) ([]ApiToken, error)
	ListUserDevices(ctx context.Context, userID pgtype.UUID) ([]Device, error)
	ListUserEmojis(ctx context.Context, arg ListUserEmojisParams) ([]CustomEmoji, error)
	ListUserPushPrefs(ctx context.Context, userID pgtype.UUID) ([]PushPref, error)
	ListUserSpaces(ctx context.Context, userID pgtype.UUID) ([]Space, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListWebhooksForEvent(ctx context.Context, arg ListWebhooksForEventParams) ([]Webhook, error)
	MaliciousURLHashes(ctx context.Context, hashes []string) ([]MaliciousURLHashesRow, error)
	MarkAllInboxRead(ctx context.Context, userID pgtype.UUID) error
	MarkEmailVerified(ctx context.Context, id pgtype.UUID) error
	MarkInboxItemRead(ctx context.Context, arg MarkInboxItemReadParams) error
	MoveChannel(ctx context.Context, arg MoveChannelParams) (Channel, error)
	OptionInPoll(ctx context.Context, arg OptionInPollParams) (bool, error)
	PollResults(ctx context.Context, pollID pgtype.UUID) ([]PollResultsRow, error)
	RemoveDMGroupMember(ctx context.Context, arg RemoveDMGroupMemberParams) error
	RemoveMemberRole(ctx context.Context, arg RemoveMemberRoleParams) error
	ResolveReport(ctx context.Context, arg ResolveReportParams) (Report, error)
	ReviewGame(ctx context.Context, arg ReviewGameParams) (Game, error)
	ReviewJoinRequest(ctx context.Context, arg ReviewJoinRequestParams) (JoinRequest, error)
	RevokeTimeout(ctx context.Context, arg RevokeTimeoutParams) error
	RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error)
	RsvpCounts(ctx context.Context, eventID pgtype.UUID) ([]RsvpCountsRow, error)
	SetChannelLock(ctx context.Context, arg SetChannelLockParams) (Channel, error)
	SetRsvp(ctx context.Context, arg SetRsvpParams) error
	SetSpaceVanity(ctx context.Context, arg SetSpaceVanityParams) (Space, error)
	SetTOTP(ctx context.Context, arg SetTOTPParams) error
	SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error
	SetUserBadges(ctx context.Context, arg SetUserBadgesParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (User, error)
	SetUserSignupIPHash(ctx context.Context, arg SetUserSignupIPHashParams) error
	SetUserStripeCustomer(ctx context.Context, arg SetUserStripeCustomerParams) error
	SetUserSubscription(ctx context.Context, arg SetUserSubscriptionParams) error
	SetWhoCanAdd(ctx context.Context, arg SetWhoCanAddParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	SubmitGame(ctx context.Context, arg SubmitGameParams) (Game, error)
	SubscribeThread(ctx context.Context, arg SubscribeThreadParams) error
	SumUserKarma(ctx context.Context, userID pgtype.UUID) (int64, error)
	TotalOwnerStorage(ctx context.Context, ownerID pgtype.UUID) (int64, error)
	TouchAPIToken(ctx context.Context, id pgtype.UUID) error
	TouchThreadActivity(ctx context.Context, id pgtype.UUID) (Thread, error)
	TransferDMGroup(ctx context.Context, arg TransferDMGroupParams) error
	TransferSpaceOwnership(ctx context.Context, arg TransferSpaceOwnershipParams) (Space, error)
	UnfollowMessage(ctx context.Context, arg UnfollowMessageParams) error
	UnsubscribeThread(ctx context.Context, arg UnsubscribeThreadParams) error
	UpdateBackupCodes(ctx context.Context, arg UpdateBackupCodesParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateChannel(ctx context.Context, arg UpdateChannelParams) (Channel, error)
	UpdateDMGroup(ctx context.Context, arg UpdateDMGroupParams) (DmGroup, error)
	UpdateFileScanStatus(ctx context.Context, arg UpdateFileScanStatusParams) error
	UpdateMemberNickname(ctx context.Context, arg UpdateMemberNicknameParams) (Member, error)
	UpdateMemberSpaceProfile(ctx context.Context, arg UpdateMemberSpaceProfileParams) (Member, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error)
	UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpsertEmailVerification(ctx context.Context, arg UpsertEmailVerificationParams) error
	UpsertJoinForm(ctx context.Context, arg UpsertJoinFormParams) (JoinForm, error)
	UpsertListing(ctx context.Context, arg UpsertListingParams) (SpaceListing, error)
	UpsertMemberOverwrite(ctx context.Context, arg UpsertMemberOverwriteParams) (ChannelOverwrite, error)
	UpsertNotifSetting(ctx context.Context, arg UpsertNotifSettingParams) (NotifSetting, error)
	UpsertPushPref(ctx context.Context, arg UpsertPushPrefParams) (PushPref, error)
	UpsertReadState(ctx context.Context, arg UpsertReadStateParams) (ChannelReadState, error)
	UpsertRoleOverwrite(ctx context.Context, arg UpsertRoleOverwriteParams) (ChannelOverwrite, error)
}

var _ Querier = (*Queries)(nil)
