// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: read_state.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listReadState = `-- name: ListReadState :many
SELECT user_id, channel_id, last_read_sort_id, last_read_archive_id, updated_at FROM channel_read_state
 WHERE user_id = $1
`

func (q *Queries) ListReadState(ctx context.Context, userID pgtype.UUID) ([]ChannelReadState, error) {
	rows, err := q.db.Query(ctx, listReadState, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelReadState{}
	for rows.Next() {
		var i ChannelReadState
		if err := rows.Scan(
			&i.UserID,
			&i.ChannelID,
			&i.LastReadSortID,
			&i.LastReadArchiveID,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertReadState = `-- name: UpsertReadState :one

INSERT INTO channel_read_state (user_id, channel_id, last_read_sort_id, last_read_archive_id, updated_at)
VALUES ($1, $2, $3, $4, NOW())
ON CONFLICT (user_id, channel_id)
    DO UPDATE SET
        last_read_sort_id = CASE
            WHEN $5::bool AND channel_read_state.last_read_sort_id >= EXCLUDED.last_read_sort_id
            THEN channel_read_state.last_read_sort_id
            ELSE EXCLUDED.last_read_sort_id END,
        last_read_archive_id = CASE
            WHEN $5::bool AND channel_read_state.last_read_sort_id >= EXCLUDED.last_read_sort_id
            THEN channel_read_state.last_read_archive_id
            ELSE EXCLUDED.last_read_archive_id END,
        updated_at = NOW()
RETURNING user_id, channel_id, last_read_sort_id, last_read_archive_id, updated_at
`

type UpsertReadStateParams struct {
	UserID            pgtype.UUID `json:"user_id"`
	ChannelID         pgtype.UUID `json:"channel_id"`
	LastReadSortID    int64       `json:"last_read_sort_id"`
	LastReadArchiveID string      `json:"last_read_archive_id"`
	AdvanceOnly       bool        `json:"advance_only"`
}

func (q *Queries) UpsertReadState(ctx context.Context, arg UpsertReadStateParams) (ChannelReadState, error) {
	row := q.db.QueryRow(ctx, upsertReadState,
		arg.UserID,
		arg.ChannelID,
		arg.LastReadSortID,
		arg.LastReadArchiveID,
		arg.AdvanceOnly,
	)
	var i ChannelReadState
	err := row.Scan(
		&i.UserID,
		&i.ChannelID,
		&i.LastReadSortID,
		&i.LastReadArchiveID,
		&i.UpdatedAt,
	)
	return i, err
}
