// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimReport = `-- name: ClaimReport :one

UPDATE reports
   SET assigned_to = $2, status = 'in_progress'
 WHERE id = $1
RETURNING id, reporter_id, target_type, target_id, reason, status, created_at, space_id, channel_id, resolved_by, resolved_at, category, context, assigned_to
`

type ClaimReportParams struct {
	ID         pgtype.UUID `json:"id"`
	AssignedTo pgtype.UUID `json:"assigned_to"`
}

func (q *Queries) ClaimReport(ctx context.Context, arg ClaimReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, claimReport, arg.ID, arg.AssignedTo)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.SpaceID,
		&i.ChannelID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Category,
		&i.Context,
		&i.AssignedTo,
	)
	return i, err
}

const countPendingReports = `-- name: CountPendingReports :one

SELECT COUNT(*) FROM reports
 WHERE space_id = $1 AND status IN ('pending', 'in_progress')
`

func (q *Queries) CountPendingReports(ctx context.Context, spaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReports, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, target_type, target_id, reason, space_id, channel_id, category, context)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, reporter_id, target_type, target_id, reason, status, created_at, space_id, channel_id, resolved_by, resolved_at, category, context, assigned_to
`

type CreateReportParams struct {
	ReporterID pgtype.UUID `json:"reporter_id"`
	TargetType string      `json:"target_type"`
	TargetID   pgtype.UUID `json:"target_id"`
	Reason     string      `json:"reason"`
	SpaceID    pgtype.UUID `json:"space_id"`
	ChannelID  pgtype.UUID `json:"channel_id"`
	Category   *string     `json:"category"`
	Context    []byte      `json:"context"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
		arg.SpaceID,
		arg.ChannelID,
		arg.Category,
		arg.Context,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.SpaceID,
		&i.ChannelID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Category,
		&i.Context,
		&i.AssignedTo,
	)
	return i, err
}

const createReportComment = `-- name: CreateReportComment :one
INSERT INTO report_comments (report_id, author_id, body)
VALUES ($1, $2, $3)
RETURNING id, report_id, author_id, body, created_at
`

type CreateReportCommentParams struct {
	ReportID pgtype.UUID `json:"report_id"`
	AuthorID pgtype.UUID `json:"author_id"`
	Body     string      `json:"body"`
}

func (q *Queries) CreateReportComment(ctx context.Context, arg CreateReportCommentParams) (ReportComment, error) {
	row := q.db.QueryRow(ctx, createReportComment, arg.ReportID, arg.AuthorID, arg.Body)
	var i ReportComment
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AuthorID,
		&i.Body,
		&i.CreatedAt,
	)
	return i, err
}

const getReport = `-- name: GetReport :one
SELECT id, reporter_id, target_type, target_id, reason, status, created_at, space_id, channel_id, resolved_by, resolved_at, category, context, assigned_to FROM reports WHERE id = $1
`

func (q *Queries) GetReport(ctx context.Context, id pgtype.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReport, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.SpaceID,
		&i.ChannelID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Category,
		&i.Context,
		&i.AssignedTo,
	)
	return i, err
}

const listReportComments = `-- name: ListReportComments :many

SELECT id, report_id, author_id, body, created_at FROM report_comments WHERE report_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListReportComments(ctx context.Context, reportID pgtype.UUID) ([]ReportComment, error) {
	rows, err := q.db.Query(ctx, listReportComments, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportComment{}
	for rows.Next() {
		var i ReportComment
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.AuthorID,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReports = `-- name: ListReports :many
SELECT id, reporter_id, target_type, target_id, reason, status, created_at, space_id, channel_id, resolved_by, resolved_at, category, context, assigned_to FROM reports
 WHERE ($3::text IS NULL OR status = $3::text)
 ORDER BY created_at DESC
 LIMIT $1 OFFSET $2
`

type ListReportsParams struct {
	Limit  int32   `json:"limit"`
	Offset int32   `json:"offset"`
	Status *string `json:"status"`
}

func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, arg.Limit, arg.Offset, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.SpaceID,
			&i.ChannelID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.Category,
			&i.Context,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceReports = `-- name: ListSpaceReports :many
SELECT id, reporter_id, target_type, target_id, reason, status, created_at, space_id, channel_id, resolved_by, resolved_at, category, context, assigned_to FROM reports
 WHERE space_id = $1
   AND ($2::text IS NULL OR status = $2::text)
   AND ($3::text IS NULL OR category = $3::text)
 ORDER BY created_at DESC
`

type ListSpaceReportsParams struct {
	SpaceID  pgtype.UUID `json:"space_id"`
	Status   *string     `json:"status"`
	Category *string     `json:"category"`
}

func (q *Queries) ListSpaceReports(ctx context.Context, arg ListSpaceReportsParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listSpaceReports, arg.SpaceID, arg.Status, arg.Category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReporterID,
			&i.TargetType,
			&i.TargetID,
			&i.Reason,
			&i.Status,
			&i.CreatedAt,
			&i.SpaceID,
			&i.ChannelID,
			&i.ResolvedBy,
			&i.ResolvedAt,
			&i.Category,
			&i.Context,
			&i.AssignedTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReport = `-- name: ResolveReport :one
UPDATE reports
   SET status = $2, resolved_by = $3, resolved_at = NOW()
 WHERE id = $1
RETURNING id, reporter_id, target_type, target_id, reason, status, created_at, space_id, channel_id, resolved_by, resolved_at, category, context, assigned_to
`

type ResolveReportParams struct {
	ID         pgtype.UUID `json:"id"`
	Status     *string     `json:"status"`
	ResolvedBy pgtype.UUID `json:"resolved_by"`
}

func (q *Queries) ResolveReport(ctx context.Context, arg ResolveReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, resolveReport, arg.ID, arg.Status, arg.ResolvedBy)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
		&i.SpaceID,
		&i.ChannelID,
		&i.ResolvedBy,
		&i.ResolvedAt,
		&i.Category,
		&i.Context,
		&i.AssignedTo,
	)
	return i, err
}
