// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :one
INSERT INTO roles (space_id, name, permissions, color, position, is_everyone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, space_id, name, permissions, color, position, is_everyone, hoist, mentionable, icon_emoji
`

type CreateRoleParams struct {
	SpaceID     pgtype.UUID `json:"space_id"`
	Name        string      `json:"name"`
	Permissions *int64      `json:"permissions"`
	Color       *string     `json:"color"`
	Position    *int32      `json:"position"`
	IsEveryone  *bool       `json:"is_everyone"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.SpaceID,
		arg.Name,
		arg.Permissions,
		arg.Color,
		arg.Position,
		arg.IsEveryone,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.Color,
		&i.Position,
		&i.IsEveryone,
		&i.Hoist,
		&i.Mentionable,
		&i.IconEmoji,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles WHERE id = $1 AND is_everyone = FALSE
`

func (q *Queries) DeleteRole(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getEveryoneRole = `-- name: GetEveryoneRole :one
SELECT id, space_id, name, permissions, color, position, is_everyone, hoist, mentionable, icon_emoji FROM roles
 WHERE space_id = $1 AND is_everyone = TRUE
 LIMIT 1
`

func (q *Queries) GetEveryoneRole(ctx context.Context, spaceID pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getEveryoneRole, spaceID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.Color,
		&i.Position,
		&i.IsEveryone,
		&i.Hoist,
		&i.Mentionable,
		&i.IconEmoji,
	)
	return i, err
}

const getMemberMaxRolePosition = `-- name: GetMemberMaxRolePosition :one

SELECT COALESCE(MAX(r.position), 0)::INT AS max_position
  FROM member_roles mr
  JOIN roles r ON r.id = mr.role_id
 WHERE mr.member_id = $1
`

func (q *Queries) GetMemberMaxRolePosition(ctx context.Context, memberID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMemberMaxRolePosition, memberID)
	var max_position int32
	err := row.Scan(&max_position)
	return max_position, err
}

const getRole = `-- name: GetRole :one
SELECT id, space_id, name, permissions, color, position, is_everyone, hoist, mentionable, icon_emoji FROM roles WHERE id = $1
`

func (q *Queries) GetRole(ctx context.Context, id pgtype.UUID) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.Color,
		&i.Position,
		&i.IsEveryone,
		&i.Hoist,
		&i.Mentionable,
		&i.IconEmoji,
	)
	return i, err
}

const listChannelOverwritesForRoles = `-- name: ListChannelOverwritesForRoles :many
SELECT channel_id, role_id, allow, deny, member_id FROM channel_overwrites
 WHERE channel_id = $1
   AND role_id = ANY($2::uuid[])
`

type ListChannelOverwritesForRolesParams struct {
	ChannelID pgtype.UUID   `json:"channel_id"`
	RoleIds   []pgtype.UUID `json:"role_ids"`
}

func (q *Queries) ListChannelOverwritesForRoles(ctx context.Context, arg ListChannelOverwritesForRolesParams) ([]ChannelOverwrite, error) {
	rows, err := q.db.Query(ctx, listChannelOverwritesForRoles, arg.ChannelID, arg.RoleIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChannelOverwrite{}
	for rows.Next() {
		var i ChannelOverwrite
		if err := rows.Scan(
			&i.ChannelID,
			&i.RoleID,
			&i.Allow,
			&i.Deny,
			&i.MemberID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberRoles = `-- name: ListMemberRoles :many
SELECT r.id, r.space_id, r.name, r.permissions, r.color, r.position, r.is_everyone, r.hoist, r.mentionable, r.icon_emoji
  FROM roles r
  JOIN member_roles mr ON mr.role_id = r.id
 WHERE mr.member_id = $1
 ORDER BY r.position
`

func (q *Queries) ListMemberRoles(ctx context.Context, memberID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listMemberRoles, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Permissions,
			&i.Color,
			&i.Position,
			&i.IsEveryone,
			&i.Hoist,
			&i.Mentionable,
			&i.IconEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionableRoleMembers = `-- name: ListMentionableRoleMembers :many
SELECT lower(r.name) AS role_name, m.user_id
  FROM roles r
  JOIN member_roles mr ON mr.role_id = r.id
  JOIN members m       ON m.id = mr.member_id
 WHERE r.space_id = $1 AND r.mentionable = TRUE AND r.is_everyone IS NOT TRUE
`

type ListMentionableRoleMembersRow struct {
	RoleName string      `json:"role_name"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListMentionableRoleMembers(ctx context.Context, spaceID pgtype.UUID) ([]ListMentionableRoleMembersRow, error) {
	rows, err := q.db.Query(ctx, listMentionableRoleMembers, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMentionableRoleMembersRow{}
	for rows.Next() {
		var i ListMentionableRoleMembersRow
		if err := rows.Scan(&i.RoleName, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoleMembers = `-- name: ListRoleMembers :many

SELECT m.id AS member_id, m.user_id, u.username, m.nickname
  FROM member_roles mr
  JOIN members m ON m.id = mr.member_id
  JOIN users u ON u.id = m.user_id
 WHERE mr.role_id = $1
 ORDER BY u.username
`

type ListRoleMembersRow struct {
	MemberID pgtype.UUID `json:"member_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Username string      `json:"username"`
	Nickname *string     `json:"nickname"`
}

func (q *Queries) ListRoleMembers(ctx context.Context, roleID pgtype.UUID) ([]ListRoleMembersRow, error) {
	rows, err := q.db.Query(ctx, listRoleMembers, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoleMembersRow{}
	for rows.Next() {
		var i ListRoleMembersRow
		if err := rows.Scan(
			&i.MemberID,
			&i.UserID,
			&i.Username,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceMemberIDs = `-- name: ListSpaceMemberIDs :many

SELECT id FROM members WHERE space_id = $1
`

func (q *Queries) ListSpaceMemberIDs(ctx context.Context, spaceID pgtype.UUID) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listSpaceMemberIDs, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var id pgtype.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaceRoles = `-- name: ListSpaceRoles :many
SELECT id, space_id, name, permissions, color, position, is_everyone, hoist, mentionable, icon_emoji FROM roles
 WHERE space_id = $1
 ORDER BY position
`

func (q *Queries) ListSpaceRoles(ctx context.Context, spaceID pgtype.UUID) ([]Role, error) {
	rows, err := q.db.Query(ctx, listSpaceRoles, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.Permissions,
			&i.Color,
			&i.Position,
			&i.IsEveryone,
			&i.Hoist,
			&i.Mentionable,
			&i.IconEmoji,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE roles
   SET name        = COALESCE($1,        name),
       permissions = COALESCE($2, permissions),
       color       = COALESCE($3,       color),
       position    = COALESCE($4,    position),
       hoist       = COALESCE($5,       hoist),
       mentionable = COALESCE($6, mentionable),
       icon_emoji  = COALESCE($7,  icon_emoji)
 WHERE id = $8
RETURNING id, space_id, name, permissions, color, position, is_everyone, hoist, mentionable, icon_emoji
`

type UpdateRoleParams struct {
	Name        *string     `json:"name"`
	Permissions *int64      `json:"permissions"`
	Color       *string     `json:"color"`
	Position    *int32      `json:"position"`
	Hoist       *bool       `json:"hoist"`
	Mentionable *bool       `json:"mentionable"`
	IconEmoji   *string     `json:"icon_emoji"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.Name,
		arg.Permissions,
		arg.Color,
		arg.Position,
		arg.Hoist,
		arg.Mentionable,
		arg.IconEmoji,
		arg.ID,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.Permissions,
		&i.Color,
		&i.Position,
		&i.IsEveryone,
		&i.Hoist,
		&i.Mentionable,
		&i.IconEmoji,
	)
	return i, err
}
