// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saves.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSavedMessage = `-- name: CreateSavedMessage :one
INSERT INTO saved_messages (user_id, channel_id, archive_id, folder)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, archive_id)
    DO UPDATE SET folder = EXCLUDED.folder, channel_id = EXCLUDED.channel_id
RETURNING id, user_id, channel_id, archive_id, folder, created_at
`

type CreateSavedMessageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	ArchiveID string      `json:"archive_id"`
	Folder    string      `json:"folder"`
}

func (q *Queries) CreateSavedMessage(ctx context.Context, arg CreateSavedMessageParams) (SavedMessage, error) {
	row := q.db.QueryRow(ctx, createSavedMessage,
		arg.UserID,
		arg.ChannelID,
		arg.ArchiveID,
		arg.Folder,
	)
	var i SavedMessage
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChannelID,
		&i.ArchiveID,
		&i.Folder,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavedMessage = `-- name: DeleteSavedMessage :execrows
DELETE FROM saved_messages
 WHERE user_id = $1 AND archive_id = $2
`

type DeleteSavedMessageParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	ArchiveID string      `json:"archive_id"`
}

func (q *Queries) DeleteSavedMessage(ctx context.Context, arg DeleteSavedMessageParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavedMessage, arg.UserID, arg.ArchiveID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSavedMessages = `-- name: ListSavedMessages :many
SELECT id, user_id, channel_id, archive_id, folder, created_at FROM saved_messages
 WHERE user_id = $1
 ORDER BY created_at DESC
`

func (q *Queries) ListSavedMessages(ctx context.Context, userID pgtype.UUID) ([]SavedMessage, error) {
	rows, err := q.db.Query(ctx, listSavedMessages, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedMessage{}
	for rows.Next() {
		var i SavedMessage
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChannelID,
			&i.ArchiveID,
			&i.Folder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
