// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: saved_searches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSavedSearches = `-- name: CountSavedSearches :one
SELECT COUNT(*) FROM saved_searches WHERE user_id = $1
`

func (q *Queries) CountSavedSearches(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSavedSearches, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSavedSearch = `-- name: CreateSavedSearch :one
INSERT INTO saved_searches (user_id, space_id, name, query)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, space_id, name, query, created_at
`

type CreateSavedSearchParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	SpaceID pgtype.UUID `json:"space_id"`
	Name    string      `json:"name"`
	Query   string      `json:"query"`
}

func (q *Queries) CreateSavedSearch(ctx context.Context, arg CreateSavedSearchParams) (SavedSearch, error) {
	row := q.db.QueryRow(ctx, createSavedSearch,
		arg.UserID,
		arg.SpaceID,
		arg.Name,
		arg.Query,
	)
	var i SavedSearch
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SpaceID,
		&i.Name,
		&i.Query,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSavedSearch = `-- name: DeleteSavedSearch :execrows
DELETE FROM saved_searches WHERE id = $1 AND user_id = $2
`

type DeleteSavedSearchParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteSavedSearch(ctx context.Context, arg DeleteSavedSearchParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSavedSearch, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listSavedSearches = `-- name: ListSavedSearches :many
SELECT id, user_id, space_id, name, query, created_at FROM saved_searches WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSavedSearches(ctx context.Context, userID pgtype.UUID) ([]SavedSearch, error) {
	rows, err := q.db.Query(ctx, listSavedSearches, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SavedSearch{}
	for rows.Next() {
		var i SavedSearch
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SpaceID,
			&i.Name,
			&i.Query,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
