// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeSession = `-- name: ConsumeSession :one

UPDATE sessions
   SET replaced_by = $1, used_at = NOW()
 WHERE refresh_token = $2 AND replaced_by IS NULL
RETURNING id, user_id, refresh_token, expires_at, created_at, family_id, replaced_by, used_at
`

type ConsumeSessionParams struct {
	ReplacedBy      pgtype.UUID `json:"replaced_by"`
	OldRefreshToken string      `json:"old_refresh_token"`
}

func (q *Queries) ConsumeSession(ctx context.Context, arg ConsumeSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, consumeSession, arg.ReplacedBy, arg.OldRefreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedBy,
		&i.UsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, refresh_token, expires_at, created_at, family_id, replaced_by, used_at
`

type CreateSessionParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.RefreshToken, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedBy,
		&i.UsedAt,
	)
	return i, err
}

const createSessionInFamily = `-- name: CreateSessionInFamily :one

INSERT INTO sessions (user_id, refresh_token, expires_at, family_id)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, refresh_token, expires_at, created_at, family_id, replaced_by, used_at
`

type CreateSessionInFamilyParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	RefreshToken string             `json:"refresh_token"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	FamilyID     pgtype.UUID        `json:"family_id"`
}

func (q *Queries) CreateSessionInFamily(ctx context.Context, arg CreateSessionInFamilyParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSessionInFamily,
		arg.UserID,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.FamilyID,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedBy,
		&i.UsedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteSessionByRefreshToken = `-- name: DeleteSessionByRefreshToken :exec
DELETE FROM sessions WHERE refresh_token = $1
`

func (q *Queries) DeleteSessionByRefreshToken(ctx context.Context, refreshToken string) error {
	_, err := q.db.Exec(ctx, deleteSessionByRefreshToken, refreshToken)
	return err
}

const deleteSessionFamily = `-- name: DeleteSessionFamily :exec

DELETE FROM sessions WHERE family_id = $1
`

func (q *Queries) DeleteSessionFamily(ctx context.Context, familyID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSessionFamily, familyID)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = $1
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserSessions, userID)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, user_id, refresh_token, expires_at, created_at, family_id, replaced_by, used_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id pgtype.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedBy,
		&i.UsedAt,
	)
	return i, err
}

const getSessionByRefreshToken = `-- name: GetSessionByRefreshToken :one
SELECT id, user_id, refresh_token, expires_at, created_at, family_id, replaced_by, used_at FROM sessions WHERE refresh_token = $1
`

func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedBy,
		&i.UsedAt,
	)
	return i, err
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions
   SET refresh_token = $1,
       expires_at    = $2
 WHERE refresh_token = $3
RETURNING id, user_id, refresh_token, expires_at, created_at, family_id, replaced_by, used_at
`

type RotateSessionParams struct {
	NewRefreshToken string             `json:"new_refresh_token"`
	NewExpiresAt    pgtype.Timestamptz `json:"new_expires_at"`
	OldRefreshToken string             `json:"old_refresh_token"`
}

func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession, arg.NewRefreshToken, arg.NewExpiresAt, arg.OldRefreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.FamilyID,
		&i.ReplacedBy,
		&i.UsedAt,
	)
	return i, err
}
