// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSpaceMembers = `-- name: CountSpaceMembers :one
SELECT COUNT(*) FROM members WHERE space_id = $1
`

func (q *Queries) CountSpaceMembers(ctx context.Context, spaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSpaceMembers, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (owner_id, name, icon_key)
VALUES ($1, $2, $3)
RETURNING id, owner_id, name, icon_key, created_at, description, rules, banner_key, tags, language, vanity_slug
`

type CreateSpaceParams struct {
	OwnerID pgtype.UUID `json:"owner_id"`
	Name    string      `json:"name"`
	IconKey *string     `json:"icon_key"`
}

func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, createSpace, arg.OwnerID, arg.Name, arg.IconKey)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
		&i.Description,
		&i.Rules,
		&i.BannerKey,
		&i.Tags,
		&i.Language,
		&i.VanitySlug,
	)
	return i, err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = $1
`

func (q *Queries) DeleteSpace(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSpace, id)
	return err
}

const getSpace = `-- name: GetSpace :one
SELECT id, owner_id, name, icon_key, created_at, description, rules, banner_key, tags, language, vanity_slug FROM spaces WHERE id = $1
`

func (q *Queries) GetSpace(ctx context.Context, id pgtype.UUID) (Space, error) {
	row := q.db.QueryRow(ctx, getSpace, id)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
		&i.Description,
		&i.Rules,
		&i.BannerKey,
		&i.Tags,
		&i.Language,
		&i.VanitySlug,
	)
	return i, err
}

const getSpaceByVanity = `-- name: GetSpaceByVanity :one
SELECT id, owner_id, name, icon_key, created_at, description, rules, banner_key, tags, language, vanity_slug FROM spaces WHERE lower(vanity_slug) = lower($1)
`

func (q *Queries) GetSpaceByVanity(ctx context.Context, lower string) (Space, error) {
	row := q.db.QueryRow(ctx, getSpaceByVanity, lower)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
		&i.Description,
		&i.Rules,
		&i.BannerKey,
		&i.Tags,
		&i.Language,
		&i.VanitySlug,
	)
	return i, err
}

const listUserSpaces = `-- name: ListUserSpaces :many
SELECT s.id, s.owner_id, s.name, s.icon_key, s.created_at, s.description, s.rules, s.banner_key, s.tags, s.language, s.vanity_slug
  FROM spaces s
  JOIN members m ON m.space_id = s.id
 WHERE m.user_id = $1
 ORDER BY s.created_at
`

func (q *Queries) ListUserSpaces(ctx context.Context, userID pgtype.UUID) ([]Space, error) {
	rows, err := q.db.Query(ctx, listUserSpaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Space{}
	for rows.Next() {
		var i Space
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.IconKey,
			&i.CreatedAt,
			&i.Description,
			&i.Rules,
			&i.BannerKey,
			&i.Tags,
			&i.Language,
			&i.VanitySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSpaceVanity = `-- name: SetSpaceVanity :one

UPDATE spaces SET vanity_slug = $2 WHERE id = $1
RETURNING id, owner_id, name, icon_key, created_at, description, rules, banner_key, tags, language, vanity_slug
`

type SetSpaceVanityParams struct {
	ID         pgtype.UUID `json:"id"`
	VanitySlug *string     `json:"vanity_slug"`
}

func (q *Queries) SetSpaceVanity(ctx context.Context, arg SetSpaceVanityParams) (Space, error) {
	row := q.db.QueryRow(ctx, setSpaceVanity, arg.ID, arg.VanitySlug)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
		&i.Description,
		&i.Rules,
		&i.BannerKey,
		&i.Tags,
		&i.Language,
		&i.VanitySlug,
	)
	return i, err
}

const transferSpaceOwnership = `-- name: TransferSpaceOwnership :one
UPDATE spaces SET owner_id = $2 WHERE id = $1
RETURNING id, owner_id, name, icon_key, created_at, description, rules, banner_key, tags, language, vanity_slug
`

type TransferSpaceOwnershipParams struct {
	ID      pgtype.UUID `json:"id"`
	OwnerID pgtype.UUID `json:"owner_id"`
}

func (q *Queries) TransferSpaceOwnership(ctx context.Context, arg TransferSpaceOwnershipParams) (Space, error) {
	row := q.db.QueryRow(ctx, transferSpaceOwnership, arg.ID, arg.OwnerID)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
		&i.Description,
		&i.Rules,
		&i.BannerKey,
		&i.Tags,
		&i.Language,
		&i.VanitySlug,
	)
	return i, err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces
   SET name        = COALESCE($1,        name),
       icon_key    = COALESCE($2,    icon_key),
       description = COALESCE($3, description),
       rules       = COALESCE($4,       rules),
       banner_key  = COALESCE($5,  banner_key),
       tags        = COALESCE($6,        tags),
       language    = COALESCE($7,    language)
 WHERE id = $8
RETURNING id, owner_id, name, icon_key, created_at, description, rules, banner_key, tags, language, vanity_slug
`

type UpdateSpaceParams struct {
	Name        *string     `json:"name"`
	IconKey     *string     `json:"icon_key"`
	Description *string     `json:"description"`
	Rules       *string     `json:"rules"`
	BannerKey   *string     `json:"banner_key"`
	Tags        []string    `json:"tags"`
	Language    *string     `json:"language"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRow(ctx, updateSpace,
		arg.Name,
		arg.IconKey,
		arg.Description,
		arg.Rules,
		arg.BannerKey,
		arg.Tags,
		arg.Language,
		arg.ID,
	)
	var i Space
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.IconKey,
		&i.CreatedAt,
		&i.Description,
		&i.Rules,
		&i.BannerKey,
		&i.Tags,
		&i.Language,
		&i.VanitySlug,
	)
	return i, err
}
