// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (space_id, channel_id, source_archive_id, title, assignee_id, due_at, created_by)
VALUES ($1, $4, $5, $2,
        $6, $7, $3)
RETURNING id, space_id, channel_id, source_archive_id, title, assignee_id, due_at, status, created_by, created_at
`

type CreateTaskParams struct {
	SpaceID         pgtype.UUID        `json:"space_id"`
	Title           string             `json:"title"`
	CreatedBy       pgtype.UUID        `json:"created_by"`
	ChannelID       pgtype.UUID        `json:"channel_id"`
	SourceArchiveID *string            `json:"source_archive_id"`
	AssigneeID      pgtype.UUID        `json:"assignee_id"`
	DueAt           pgtype.Timestamptz `json:"due_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.SpaceID,
		arg.Title,
		arg.CreatedBy,
		arg.ChannelID,
		arg.SourceArchiveID,
		arg.AssigneeID,
		arg.DueAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.SourceArchiveID,
		&i.Title,
		&i.AssigneeID,
		&i.DueAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTask = `-- name: GetTask :one
SELECT id, space_id, channel_id, source_archive_id, title, assignee_id, due_at, status, created_by, created_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.SourceArchiveID,
		&i.Title,
		&i.AssigneeID,
		&i.DueAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceTasks = `-- name: ListSpaceTasks :many
SELECT id, space_id, channel_id, source_archive_id, title, assignee_id, due_at, status, created_by, created_at FROM tasks
 WHERE space_id = $1
 ORDER BY (status = 'done'), created_at DESC
 LIMIT $2
`

type ListSpaceTasksParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Limit   int32       `json:"limit"`
}

func (q *Queries) ListSpaceTasks(ctx context.Context, arg ListSpaceTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, listSpaceTasks, arg.SpaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.SourceArchiveID,
			&i.Title,
			&i.AssigneeID,
			&i.DueAt,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
   SET title       = COALESCE($1, title),
       status      = COALESCE($2, status),
       assignee_id = COALESCE($3, assignee_id),
       due_at      = COALESCE($4, due_at)
 WHERE id = $5
RETURNING id, space_id, channel_id, source_archive_id, title, assignee_id, due_at, status, created_by, created_at
`

type UpdateTaskParams struct {
	Title      *string            `json:"title"`
	Status     *string            `json:"status"`
	AssigneeID pgtype.UUID        `json:"assignee_id"`
	DueAt      pgtype.Timestamptz `json:"due_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.Title,
		arg.Status,
		arg.AssigneeID,
		arg.DueAt,
		arg.ID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.SourceArchiveID,
		&i.Title,
		&i.AssigneeID,
		&i.DueAt,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
