// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: threads.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createThread = `-- name: CreateThread :one
INSERT INTO threads (channel_id, root_archive_id, title, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, channel_id, root_archive_id, title, created_by, created_at, last_activity_at
`

type CreateThreadParams struct {
	ChannelID     pgtype.UUID `json:"channel_id"`
	RootArchiveID string      `json:"root_archive_id"`
	Title         string      `json:"title"`
	CreatedBy     pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (Thread, error) {
	row := q.db.QueryRow(ctx, createThread,
		arg.ChannelID,
		arg.RootArchiveID,
		arg.Title,
		arg.CreatedBy,
	)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.RootArchiveID,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, channel_id, root_archive_id, title, created_by, created_at, last_activity_at FROM threads WHERE id = $1
`

func (q *Queries) GetThread(ctx context.Context, id pgtype.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, getThread, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.RootArchiveID,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const listChannelThreads = `-- name: ListChannelThreads :many
SELECT t.id, t.channel_id, t.root_archive_id, t.title, t.created_by, t.created_at, t.last_activity_at,
       (s.user_id IS NOT NULL)::bool AS is_subscribed
  FROM threads t
  LEFT JOIN thread_subscriptions s
         ON s.thread_id = t.id AND s.user_id = $1
 WHERE t.channel_id = $2
 ORDER BY t.last_activity_at DESC
`

type ListChannelThreadsParams struct {
	ViewerID  pgtype.UUID `json:"viewer_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
}

type ListChannelThreadsRow struct {
	Thread       Thread `json:"thread"`
	IsSubscribed bool   `json:"is_subscribed"`
}

func (q *Queries) ListChannelThreads(ctx context.Context, arg ListChannelThreadsParams) ([]ListChannelThreadsRow, error) {
	rows, err := q.db.Query(ctx, listChannelThreads, arg.ViewerID, arg.ChannelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListChannelThreadsRow{}
	for rows.Next() {
		var i ListChannelThreadsRow
		if err := rows.Scan(
			&i.Thread.ID,
			&i.Thread.ChannelID,
			&i.Thread.RootArchiveID,
			&i.Thread.Title,
			&i.Thread.CreatedBy,
			&i.Thread.CreatedAt,
			&i.Thread.LastActivityAt,
			&i.IsSubscribed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribeThread = `-- name: SubscribeThread :exec
INSERT INTO thread_subscriptions (user_id, thread_id)
VALUES ($1, $2)
ON CONFLICT (user_id, thread_id) DO NOTHING
`

type SubscribeThreadParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ThreadID pgtype.UUID `json:"thread_id"`
}

func (q *Queries) SubscribeThread(ctx context.Context, arg SubscribeThreadParams) error {
	_, err := q.db.Exec(ctx, subscribeThread, arg.UserID, arg.ThreadID)
	return err
}

const touchThreadActivity = `-- name: TouchThreadActivity :one
UPDATE threads SET last_activity_at = NOW() WHERE id = $1 RETURNING id, channel_id, root_archive_id, title, created_by, created_at, last_activity_at
`

func (q *Queries) TouchThreadActivity(ctx context.Context, id pgtype.UUID) (Thread, error) {
	row := q.db.QueryRow(ctx, touchThreadActivity, id)
	var i Thread
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.RootArchiveID,
		&i.Title,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const unsubscribeThread = `-- name: UnsubscribeThread :exec
DELETE FROM thread_subscriptions WHERE user_id = $1 AND thread_id = $2
`

type UnsubscribeThreadParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	ThreadID pgtype.UUID `json:"thread_id"`
}

func (q *Queries) UnsubscribeThread(ctx context.Context, arg UnsubscribeThreadParams) error {
	_, err := q.db.Exec(ctx, unsubscribeThread, arg.UserID, arg.ThreadID)
	return err
}
