// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAccountsBySignupIPHash = `-- name: CountAccountsBySignupIPHash :one
SELECT COUNT(*) FROM users WHERE signup_ip_hash = $1
`

func (q *Queries) CountAccountsBySignupIPHash(ctx context.Context, signupIpHash *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAccountsBySignupIPHash, signupIpHash)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createBannedIdentifier = `-- name: CreateBannedIdentifier :exec
INSERT INTO banned_identifiers (kind, value, reason, banned_by)
VALUES ($1, LOWER($2), $3, $4)
ON CONFLICT (kind, value) DO NOTHING
`

type CreateBannedIdentifierParams struct {
	Kind     string      `json:"kind"`
	Lower    string      `json:"lower"`
	Reason   *string     `json:"reason"`
	BannedBy pgtype.UUID `json:"banned_by"`
}

func (q *Queries) CreateBannedIdentifier(ctx context.Context, arg CreateBannedIdentifierParams) error {
	_, err := q.db.Exec(ctx, createBannedIdentifier,
		arg.Kind,
		arg.Lower,
		arg.Reason,
		arg.BannedBy,
	)
	return err
}

const createOAuthAccount = `-- name: CreateOAuthAccount :one
INSERT INTO oauth_accounts (user_id, provider, provider_id)
VALUES ($1, $2, $3)
RETURNING id, user_id, provider, provider_id
`

type CreateOAuthAccountParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	Provider   string      `json:"provider"`
	ProviderID string      `json:"provider_id"`
}

func (q *Queries) CreateOAuthAccount(ctx context.Context, arg CreateOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, createOAuthAccount, arg.UserID, arg.Provider, arg.ProviderID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified
`

type CreateUserParams struct {
	Username     string  `json:"username"`
	Email        string  `json:"email"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.Disabled,
		&i.WhoCanAdd,
		&i.BannerKey,
		&i.Bio,
		&i.Pronouns,
		&i.Links,
		&i.AccentColor,
		&i.SignupIpHash,
		&i.Badges,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.EmailVerified,
	)
	return i, err
}

const deleteEmailVerification = `-- name: DeleteEmailVerification :exec
DELETE FROM email_verifications WHERE user_id = $1
`

func (q *Queries) DeleteEmailVerification(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteEmailVerification, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const disableTOTP = `-- name: DisableTOTP :exec
UPDATE users SET totp_secret = NULL, totp_enabled = false, backup_codes = NULL WHERE id = $1
`

func (q *Queries) DisableTOTP(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableTOTP, id)
	return err
}

const getEmailVerification = `-- name: GetEmailVerification :one
SELECT code_hash, expires_at FROM email_verifications WHERE user_id = $1
`

type GetEmailVerificationRow struct {
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) GetEmailVerification(ctx context.Context, userID pgtype.UUID) (GetEmailVerificationRow, error) {
	row := q.db.QueryRow(ctx, getEmailVerification, userID)
	var i GetEmailVerificationRow
	err := row.Scan(&i.CodeHash, &i.ExpiresAt)
	return i, err
}

const getOAuthAccount = `-- name: GetOAuthAccount :one
SELECT id, user_id, provider, provider_id FROM oauth_accounts
WHERE provider = $1 AND provider_id = $2
`

type GetOAuthAccountParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetOAuthAccount(ctx context.Context, arg GetOAuthAccountParams) (OauthAccount, error) {
	row := q.db.QueryRow(ctx, getOAuthAccount, arg.Provider, arg.ProviderID)
	var i OauthAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderID,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.Disabled,
		&i.WhoCanAdd,
		&i.BannerKey,
		&i.Bio,
		&i.Pronouns,
		&i.Links,
		&i.AccentColor,
		&i.SignupIpHash,
		&i.Badges,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.Disabled,
		&i.WhoCanAdd,
		&i.BannerKey,
		&i.Bio,
		&i.Pronouns,
		&i.Links,
		&i.AccentColor,
		&i.SignupIpHash,
		&i.Badges,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.EmailVerified,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified FROM users WHERE LOWER(username) = LOWER($1)
`

func (q *Queries) GetUserByUsername(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.Disabled,
		&i.WhoCanAdd,
		&i.BannerKey,
		&i.Bio,
		&i.Pronouns,
		&i.Links,
		&i.AccentColor,
		&i.SignupIpHash,
		&i.Badges,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.EmailVerified,
	)
	return i, err
}

const isIdentifierBanned = `-- name: IsIdentifierBanned :one
SELECT EXISTS (
    SELECT 1 FROM banned_identifiers
     WHERE (kind = 'email' AND value = LOWER($1))
        OR (kind = 'username' AND value = LOWER($2))
)
`

type IsIdentifierBannedParams struct {
	Lower   string `json:"lower"`
	Lower_2 string `json:"lower_2"`
}

func (q *Queries) IsIdentifierBanned(ctx context.Context, arg IsIdentifierBannedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isIdentifierBanned, arg.Lower, arg.Lower_2)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified FROM users ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.PasswordHash,
			&i.AvatarKey,
			&i.CreatedAt,
			&i.DisplayName,
			&i.Status,
			&i.IsAdmin,
			&i.Disabled,
			&i.WhoCanAdd,
			&i.BannerKey,
			&i.Bio,
			&i.Pronouns,
			&i.Links,
			&i.AccentColor,
			&i.SignupIpHash,
			&i.Badges,
			&i.Tier,
			&i.StripeCustomerID,
			&i.StripeSubscriptionID,
			&i.SubscriptionStatus,
			&i.CurrentPeriodEnd,
			&i.TotpSecret,
			&i.TotpEnabled,
			&i.BackupCodes,
			&i.EmailVerified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE users SET email_verified = true WHERE id = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markEmailVerified, id)
	return err
}

const setTOTP = `-- name: SetTOTP :exec
UPDATE users SET totp_secret = $2, totp_enabled = $3, backup_codes = $4 WHERE id = $1
`

type SetTOTPParams struct {
	ID          pgtype.UUID `json:"id"`
	TotpSecret  *string     `json:"totp_secret"`
	TotpEnabled bool        `json:"totp_enabled"`
	BackupCodes []byte      `json:"backup_codes"`
}

func (q *Queries) SetTOTP(ctx context.Context, arg SetTOTPParams) error {
	_, err := q.db.Exec(ctx, setTOTP,
		arg.ID,
		arg.TotpSecret,
		arg.TotpEnabled,
		arg.BackupCodes,
	)
	return err
}

const setUserAdmin = `-- name: SetUserAdmin :exec
UPDATE users SET is_admin = $2 WHERE id = $1
`

type SetUserAdminParams struct {
	ID      pgtype.UUID `json:"id"`
	IsAdmin bool        `json:"is_admin"`
}

func (q *Queries) SetUserAdmin(ctx context.Context, arg SetUserAdminParams) error {
	_, err := q.db.Exec(ctx, setUserAdmin, arg.ID, arg.IsAdmin)
	return err
}

const setUserBadges = `-- name: SetUserBadges :exec
UPDATE users SET badges = $2 WHERE id = $1
`

type SetUserBadgesParams struct {
	ID     pgtype.UUID `json:"id"`
	Badges []string    `json:"badges"`
}

func (q *Queries) SetUserBadges(ctx context.Context, arg SetUserBadgesParams) error {
	_, err := q.db.Exec(ctx, setUserBadges, arg.ID, arg.Badges)
	return err
}

const setUserDisabled = `-- name: SetUserDisabled :one
UPDATE users SET disabled = $2 WHERE id = $1 RETURNING id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified
`

type SetUserDisabledParams struct {
	ID       pgtype.UUID `json:"id"`
	Disabled bool        `json:"disabled"`
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserDisabled, arg.ID, arg.Disabled)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.Disabled,
		&i.WhoCanAdd,
		&i.BannerKey,
		&i.Bio,
		&i.Pronouns,
		&i.Links,
		&i.AccentColor,
		&i.SignupIpHash,
		&i.Badges,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.EmailVerified,
	)
	return i, err
}

const setUserSignupIPHash = `-- name: SetUserSignupIPHash :exec
UPDATE users SET signup_ip_hash = $2 WHERE id = $1
`

type SetUserSignupIPHashParams struct {
	ID           pgtype.UUID `json:"id"`
	SignupIpHash *string     `json:"signup_ip_hash"`
}

func (q *Queries) SetUserSignupIPHash(ctx context.Context, arg SetUserSignupIPHashParams) error {
	_, err := q.db.Exec(ctx, setUserSignupIPHash, arg.ID, arg.SignupIpHash)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec

UPDATE users
SET username = $2, email = $3, password_hash = NULL, avatar_key = NULL, banner_key = NULL, bio = NULL, links = '[]'::jsonb, disabled = true
WHERE id = $1
`

type SoftDeleteUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Email    string      `json:"email"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.ID, arg.Username, arg.Email)
	return err
}

const updateBackupCodes = `-- name: UpdateBackupCodes :exec
UPDATE users SET backup_codes = $2 WHERE id = $1
`

type UpdateBackupCodesParams struct {
	ID          pgtype.UUID `json:"id"`
	BackupCodes []byte      `json:"backup_codes"`
}

func (q *Queries) UpdateBackupCodes(ctx context.Context, arg UpdateBackupCodesParams) error {
	_, err := q.db.Exec(ctx, updateBackupCodes, arg.ID, arg.BackupCodes)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_key = $2 WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID        pgtype.UUID `json:"id"`
	AvatarKey *string     `json:"avatar_key"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.AvatarKey)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           pgtype.UUID `json:"id"`
	PasswordHash *string     `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
   SET display_name = COALESCE($1, display_name),
       status       = COALESCE($2, status),
       avatar_key   = COALESCE($3, avatar_key),
       banner_key   = COALESCE($4, banner_key),
       bio          = COALESCE($5, bio),
       pronouns     = COALESCE($6, pronouns),
       links        = COALESCE($7, links),
       accent_color = COALESCE($8, accent_color)
 WHERE id = $9
RETURNING id, username, email, password_hash, avatar_key, created_at, display_name, status, is_admin, disabled, who_can_add, banner_key, bio, pronouns, links, accent_color, signup_ip_hash, badges, tier, stripe_customer_id, stripe_subscription_id, subscription_status, current_period_end, totp_secret, totp_enabled, backup_codes, email_verified
`

type UpdateUserProfileParams struct {
	DisplayName *string     `json:"display_name"`
	Status      *string     `json:"status"`
	AvatarKey   *string     `json:"avatar_key"`
	BannerKey   *string     `json:"banner_key"`
	Bio         *string     `json:"bio"`
	Pronouns    *string     `json:"pronouns"`
	Links       []byte      `json:"links"`
	AccentColor *string     `json:"accent_color"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Status,
		arg.AvatarKey,
		arg.BannerKey,
		arg.Bio,
		arg.Pronouns,
		arg.Links,
		arg.AccentColor,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.AvatarKey,
		&i.CreatedAt,
		&i.DisplayName,
		&i.Status,
		&i.IsAdmin,
		&i.Disabled,
		&i.WhoCanAdd,
		&i.BannerKey,
		&i.Bio,
		&i.Pronouns,
		&i.Links,
		&i.AccentColor,
		&i.SignupIpHash,
		&i.Badges,
		&i.Tier,
		&i.StripeCustomerID,
		&i.StripeSubscriptionID,
		&i.SubscriptionStatus,
		&i.CurrentPeriodEnd,
		&i.TotpSecret,
		&i.TotpEnabled,
		&i.BackupCodes,
		&i.EmailVerified,
	)
	return i, err
}

const upsertEmailVerification = `-- name: UpsertEmailVerification :exec
INSERT INTO email_verifications (user_id, code_hash, expires_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET code_hash = $2, expires_at = $3, created_at = NOW()
`

type UpsertEmailVerificationParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) UpsertEmailVerification(ctx context.Context, arg UpsertEmailVerificationParams) error {
	_, err := q.db.Exec(ctx, upsertEmailVerification, arg.UserID, arg.CodeHash, arg.ExpiresAt)
	return err
}
