// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: webhooks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (space_id, channel_id, name, url, secret, events)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, space_id, channel_id, name, url, secret, events, created_at
`

type CreateWebhookParams struct {
	SpaceID   pgtype.UUID `json:"space_id"`
	ChannelID pgtype.UUID `json:"channel_id"`
	Name      string      `json:"name"`
	Url       string      `json:"url"`
	Secret    *string     `json:"secret"`
	Events    []string    `json:"events"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.SpaceID,
		arg.ChannelID,
		arg.Name,
		arg.Url,
		arg.Secret,
		arg.Events,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getWebhook = `-- name: GetWebhook :one
SELECT id, space_id, channel_id, name, url, secret, events, created_at FROM webhooks WHERE id = $1
`

func (q *Queries) GetWebhook(ctx context.Context, id pgtype.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhook, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.CreatedAt,
	)
	return i, err
}

const listSpaceWebhooks = `-- name: ListSpaceWebhooks :many
SELECT id, space_id, channel_id, name, url, secret, events, created_at FROM webhooks WHERE space_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSpaceWebhooks(ctx context.Context, spaceID pgtype.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listSpaceWebhooks, spaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebhooksForEvent = `-- name: ListWebhooksForEvent :many

SELECT id, space_id, channel_id, name, url, secret, events, created_at FROM webhooks
 WHERE space_id = $1
   AND $2::TEXT = ANY(events)
`

type ListWebhooksForEventParams struct {
	SpaceID pgtype.UUID `json:"space_id"`
	Event   string      `json:"event"`
}

func (q *Queries) ListWebhooksForEvent(ctx context.Context, arg ListWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksForEvent, arg.SpaceID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.ChannelID,
			&i.Name,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
   SET name       = COALESCE($1,       name),
       url        = COALESCE($2,        url),
       channel_id = COALESCE($3, channel_id),
       events     = COALESCE($4,     events)
 WHERE id = $5
RETURNING id, space_id, channel_id, name, url, secret, events, created_at
`

type UpdateWebhookParams struct {
	Name      *string     `json:"name"`
	Url       *string     `json:"url"`
	ChannelID pgtype.UUID `json:"channel_id"`
	Events    []string    `json:"events"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.Name,
		arg.Url,
		arg.ChannelID,
		arg.Events,
		arg.ID,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.ChannelID,
		&i.Name,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.CreatedAt,
	)
	return i, err
}
