// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: xmpp_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeXMPPToken = `-- name: ConsumeXMPPToken :one

DELETE FROM xmpp_tokens
 WHERE token = $1 AND expires_at > NOW()
RETURNING token, user_id, expires_at, created_at
`

func (q *Queries) ConsumeXMPPToken(ctx context.Context, token string) (XmppToken, error) {
	row := q.db.QueryRow(ctx, consumeXMPPToken, token)
	var i XmppToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createXMPPToken = `-- name: CreateXMPPToken :one
INSERT INTO xmpp_tokens (token, user_id, expires_at)
VALUES ($1, $2, $3)
RETURNING token, user_id, expires_at, created_at
`

type CreateXMPPTokenParams struct {
	Token     string             `json:"token"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateXMPPToken(ctx context.Context, arg CreateXMPPTokenParams) (XmppToken, error) {
	row := q.db.QueryRow(ctx, createXMPPToken, arg.Token, arg.UserID, arg.ExpiresAt)
	var i XmppToken
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredXMPPTokens = `-- name: DeleteExpiredXMPPTokens :exec
DELETE FROM xmpp_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredXMPPTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredXMPPTokens)
	return err
}
